DROP TABLE IF EXISTS mmd.MMD_EVENT_MASTER;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_EVENT_MASTER(
EVENT_ID int, 
EVENT_CODE int, 
EVENT_NAME string, 
DESCRIPTION string, 
TAMPER_FLAG string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_EVENT_NOTIFICATION;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_EVENT_NOTIFICATION(
EVENT_NOTE_ID int, 
EVENT_ID int, 
NOTIFICATION_REQ string, 
ONSCREEN_FLAG string, 
SMS_FLAG string, 
EMAIL_FLAG string, 
DESIGNATION_CODE string, 
PERSONAL_MOBILE int, 
EMAIL_ADDRESS string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




DROP TABLE IF EXISTS mmd.MMD_FEEDERS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_FEEDERS(
FEEDER_ID int, 
CODE string, 
NAME string, 
CAPACITY string, 
SUBSTATION_ID int, 
ALT_FEDDER_CODE string, 
CONDUCTOR_TYPE string, 
LINELENGTH bigint, 
LENGTHUNIT string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE, 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.MMD_FEEDER_DTRS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_FEEDER_DTRS(
FDTR_ID int, 
SFDR_ID int, 
DTR_ID int, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE, 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_FUNCTION;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_FUNCTION(
FUNCTION_ID int, 
FUNCTION_NAME string, 
DESCRIPTION string, 
SHORT_NAME string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_FUNCTION_ROLE;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_FUNCTION_ROLE(
FUNC_ROLE_ID int, 
FUNCTION_ID int, 
ROLE_ID int, 
READ string, 
WRITE string, 
SHOW string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_GPS_LOC;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_GPS_LOC(
GPSLOC_ID int, 
LONGITUDE string, 
LATITUDE string, 
VALIDATED string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.MMD_LOOKUP_VALUE;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_LOOKUP_VALUE(
LOOKUP_ID int, 
LOOKUP_TYPE string, 
LOOKUP_CODE string, 
MEANING string, 
DESCRIPTION string, 
ENABLED_FLAG string, 
START_DATE_ACTIVE DATE, 
END_DATE_ACTIVE DATE, 
CREATED_BY int, 
CREATION_DATE DATE, 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_LOOKUP_VALUES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_LOOKUP_VALUES(
LOOKUP_ID int, 
LOOKUP_TYPE string, 
LOOKUP_CODE string, 
MEANING string, 
DESCRIPTION string, 
ENABLED_FLAG string, 
START_DATE_ACTIVE DATE, 
END_DATE_ACTIVE DATE, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_MAPP_USERS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_MAPP_USERS(
MAPP_USER_ID int, 
UKSCNO string, 
EMAILID string, 
CONSUMER_MOBILENO string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE, 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.MMD_MD_STATUS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_MD_STATUS(
STATUS_ID int, 
CODE int, 
MTR_STATUS string, 
ITEM_TYPE string, 
DESCRIPTION string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_MENU;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_MENU(
MENU_ID int, 
MENU_NAME string, 
DESCRIPTION string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_MENU_FUNCTION;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_MENU_FUNCTION(
MENU_FUNCTION_ID int, 
MENU_ID int, 
FUNCTION_ID int, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_MENU_ROLE;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_MENU_ROLE(
MENU_ROLE_ID int, 
MENU_ID int, 
ROLE_ID int, 
READ string, 
WRITE string, 
SHOW string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_MENU_ROLE_CNV;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_MENU_ROLE_CNV(
MENU string, 
READ_M string, 
WRITE_M string, 
SHOW_M string, 
MENU_DESCRIPTION string, 
SUBMENU string, 
READ_F string, 
WRITE_F string, 
SHOW_F string, 
FUNCTION_DESCRIPTION string, 
USER_ROLES string, 
USER_ID string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_METER;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_METER(
METER_ID int, 
MTR_NO int, 
TYPE_ID int, 
MTR_CAPACITY bigint, 
GPS_LOC_ID int, 
MTR_PHASE string, 
ACTIVE_CONSTANT bigint, 
REACTIVE_CONSTANT bigint, 
MTR_MAKE_ID int, 
KWH_RDG bigint, 
KVARH_RDG bigint, 
KVAH_RDG bigint, 
DEMAND bigint, 
MF bigint, 
RF bigint, 
CT_RATIO_NUMERATOR bigint, 
CT_RATIO_DENOMINATOR bigint, 
VT_RATIO_NUMERATOR bigint, 
VT_RATIO_DENOMINATOR bigint, 
MTR_SLNO bigint, 
MTR_SEALNO1 bigint, 
MTR_SEALNO2 bigint, 
MTR_SEALNO3 bigint, 
MTR_SEALNO4 bigint, 
MTR_SEALDT bigint, 
MTR_DIGITS bigint, 
MTR_DECIMAL bigint, 
TERMINAL_SEALNO_1 bigint, 
TERMINAL_SEALNO_2 bigint, 
TOU_FLAG string, 
MTR_MFG_DATE DATE, 
MTR_FAILURE_DATE DATE, 
MTR_ISSUED_DATE DATE, 
MTR_INSTALLED_DATE DATE, 
COMMISSIONED_DATE DATE, 
HDLC_ADDRESS string, 
MTR_REGISTRATION_TIME TIMESTAMP, 
AUTO_BREAKER_AVAILABLE string, 
BREAKER_ENABLED string, 
MCB_TYPE string, 
SEC_ITEM_int bigint, 
LOAD_PROFILE_INTERVAL bigint, 
CURRENT_OVERLIMIT_THRESHOLD bigint, 
CURRENT_OVERLIMIT_DURATION bigint, 
VOLTAGE_UNDERLIMIT_THRESHOLD bigint, 
VOLTAGE_UNDERLIMIT_DURATION bigint, 
AVG_PF_THRESHOLD bigint, 
MTR_LOCATION string, 
RELAY_STATUS string, 
INTEGRATION_METHOD string, 
EOB_DATE DATE, 
PROTOCOL_ID int, 
CATEGORY_ID int, 
CATEGORY_TYPE_ID int, 
STATUS_ID int, 
MTR_ACCURACY_ID int, 
MTR_MODEL_ID int, 
MTR_CONN_TYPE_ID int, 
DIP_ID int, 
LPC_ID int, 
CT_FACTOR int, 
VT_FACTOR int, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string, 
LIVE_PHASE string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_METERS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_METERS(
METER_ID int, 
MTR_NO string, 
TYPE_ID int, 
MTR_CONN_TYPE_ID int, 
MTR_MAKE_ID int, 
MTR_ACCURACY_ID int, 
MTR_MODEL_ID int, 
PROTOCOL_ID int, 
CATEGORY_ID int, 
CATEGORY_TYPE_ID int, 
STATUS_ID int, 
DIP_ID int, 
LPC_ID int, 
MTR_INSTALLED_DATE DATE, 
COMMISSIONED_DATE DATE, 
MTR_PHASE string, 
TOU_FLAG string, 
GPS_LOC_ID int, 
LATITUDE string, 
LONGITUDE string, 
CT_FACTOR int, 
VT_FACTOR int, 
KWH_RDG bigint, 
KVARH_RDG bigint, 
KVAH_RDG bigint, 
MF bigint, 
RF bigint, 
CT_RATIO_NUMERATOR bigint, 
CT_RATIO_DENOMINATOR bigint, 
VT_RATIO_NUMERATOR bigint, 
VT_RATIO_DENOMINATOR bigint, 
MTR_MFG_DATE DATE, 
MTR_ISSUED_DATE DATE, 
MTR_CAPACITY bigint, 
ACTIVE_CONSTANT bigint, 
REACTIVE_CONSTANT bigint, 
MTR_SLNO bigint, 
MTR_SEALNO1 bigint, 
MTR_SEALNO2 bigint, 
MTR_SEALNO3 bigint, 
MTR_SEALNO4 bigint, 
MTR_SEALDT bigint, 
MTR_DIGITS bigint, 
MTR_DECIMAL bigint, 
TERMINAL_SEALNO_1 bigint, 
TERMINAL_SEALNO_2 bigint, 
HDLC_ADDRESS string, 
MTR_REGISTRATION_TIME TIMESTAMP, 
AUTO_BREAKER_AVAILABLE string, 
BREAKER_ENABLED string, 
MCB_TYPE string, 
SEC_ITEM_int bigint, 
LOAD_PROFILE_INTERVAL bigint, 
CURRENT_OVERLIMIT_THRESHOLD bigint, 
CURRENT_OVERLIMIT_DURATION bigint, 
VOLTAGE_UNDERLIMIT_THRESHOLD bigint, 
VOLTAGE_UNDERLIMIT_DURATION bigint, 
AVG_PF_THRESHOLD bigint, 
MTR_LOCATION string, 
RELAY_STATUS string, 
INTEGRATION_METHOD string, 
EOB_DATE DATE, 
LIVE_PHASE string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string, 
INACTIVE_FLAG int, 
DEMAND bigint, 
MTR_FAILURE_DATE DATE, 
METER_LOAD_STATUS string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_METER_ACCESSORY;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_METER_ACCESSORY(
ID int, 
METER_ID int, 
ACCESSORY_ID int, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE, 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_METER_CONSUMER;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_METER_CONSUMER(
MTR_CONSUMER_ID int, 
METER_ID int, 
CONSUMER_ID int, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE, 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_METER_CONSUMERS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_METER_CONSUMERS(
MTR_CONSUMER_ID int, 
METER_ID int, 
CONSUMER_ID int, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE, 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_METER_FIELDDEVICE;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_METER_FIELDDEVICE(
ID int, 
METER_ID int, 
FIELD_DEVICE_ID int, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE, 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_METER_HISTORY;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_METER_HISTORY(
METER_HIS_ID int, 
OLD_MTR_NO string, 
METER_STATUS string, 
CHANGE_REASON string, 
FAILURE_DATE DATE, 
KWH_RDG bigint, 
KVARH_RDG bigint, 
KVAH_RDG bigint, 
DEMAND bigint, 
OLD_HLDC_ADDRESS string, 
OLD_ACTIVE_CONSTANT bigint, 
OLD_REACTIVE_CONSTANT bigint, 
OLD_CT_RATIO_NUMERATOR bigint, 
OLD_CT_RATIO_DENOMINATOR bigint, 
OLD_VT_RATIO_NUMERATOR bigint, 
OLD_VT_RATIO_DENOMINATOR bigint, 
OLD_PROFILE_INTERVAL bigint, 
OLD_CURRENT_OVERLIMIT_TH bigint, 
OLD_CURRENT_OVERLIMIT_DUR bigint, 
OLD_VOLTAGE_UNDERLIMIT_TH bigint, 
OLD_VOLTAGE_UNDERLIMIT_DUR bigint, 
OLD_AVG_PF_THRESHOLD bigint, 
OLD_EOB_DATE DATE, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE, 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.MMD_METER_MASTER_CNV;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_METER_MASTER_CNV(
ERO_NAME string, 
DIVISION string, 
SUBDIV string, 
SECTION string, 
CAT string, 
AREACD string, 
SCNO string, 
UKSCNO string, 
NAME string, 
ADD1 string, 
ADD2 string, 
ADD3 string, 
ADD4 string, 
LOAD string, 
ST string, 
MTRNO string, 
MAKE string, 
STRCD string, 
STRUCTNAME string, 
FDRCD string, 
FDRNAME string, 
SUB_STATION string, 
CIRCLE string, 
DISCOM string, 
REGION string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.MMD_METER_TYPE;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_METER_TYPE(
TYPE_NAME string, 
ITEM_TYPE string, 
DESCRIPTION string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_MTR_ACCURACY;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_MTR_ACCURACY(
MTR_ACCURACY_ID int, 
MTR_ACCURACY string, 
DESCRIPTION string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_MTR_MAKE;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_MTR_MAKE(
MTR_MAKE_ID int, 
MTR_MAKE_ORG_CODE string, 
MTR_MAKE_ORG_NAME string, 
ITEM_TYPE string, 
DESCRIPTION string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE, 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_MTR_MODEL;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_MTR_MODEL(
MTR_MODEL_ID int, 
MTR_MODEL string, 
DESCRIPTION string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_MTR_PROTOCOL;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_MTR_PROTOCOL(
PROTOCOL_ID int, 
NAME string, 
PROTOCOL_TYPE string, 
DESCRIPTION string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE, 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_MTR_TYPE;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_MTR_TYPE(
TYPE_ID int, 
TYPE_NAME string, 
ITEM_TYPE string, 
DESCRIPTION string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_ONDEMAND_STATUS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_ONDEMAND_STATUS(
OND_STATUS_ID int, 
METER_ID int, 
METER_LOAD_STATUS string, 
MESSAGE_ID string, 
MESSAGE_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_ROLES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_ROLES(
ROLE_ID int, 
ROLE_NAME string, 
DESCRIPTION string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_SDP_DCU;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_SDP_DCU(
SDP_ID int, 
DCU_ID int, 
SDP_NUM string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_SDP_METER;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_SDP_METER(
SDP_ID int, 
METER_ID int, 
SDP_NUM string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.MMD_SECTION_SUBSTATIONS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_SECTION_SUBSTATIONS(
SECTION_SUBSTATION_ID int, 
SECTION_ID int, 
SUBSTATION_ID int, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.MMD_SIM;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_SIM(
SIM_ID int, 
VENDOR_ID int, 
SIM_NO int, 
SERVICE_TYPE_ID int, 
MOBILE_NO int, 
TYPE_OF_IP string, 
IP_TYPE string, 
APN_NAME string, 
APN_USERNAME string, 
APN_PASSWORD string, 
IPADDRSS string, 
DATA_CALL_ENABLED string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.MMD_SUBGROUP_PARA_MAP;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_SUBGROUP_PARA_MAP(
SDM_ID int, 
GROUP_ID int, 
PARAMETER string, 
DLMS_CODE string, 
UNIT string, 
DESCRIPTION string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.MMD_SUBSTATION;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_SUBSTATION(
SUBSTATION_ID int, 
ADMIN_ENTITY_VALUE_ID int, 
CODE string, 
NAME string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.MMD_SUBSTATIONS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_SUBSTATIONS(
SUBSTATION_ID int, 
CODE string, 
NAME string, 
CAPACITY string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.MMD_SUBSTATION_FEEDER;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_SUBSTATION_FEEDER(
SFDR_ID int, 
SECTION_SUBSTATION_ID int, 
FEEDER_ID int, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE, 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.MMD_TOU_HOLIDAYS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_TOU_HOLIDAYS(
HOLIDAY_ID int, 
ADMIN_ENTITY_VALUE_ID int, 
HOLIDAY string, 
HOLIDAY_DATE DATE, 
MAX_DEMAND_BLOCK string, 
FIRMWARE_VERSION int, 
DESCRIPTION string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string, 
ORDER_H int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_TOU_SEASONS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_TOU_SEASONS(
SEASON_ID int, 
ADMIN_ENTITY_VALUE_ID int, 
SEASON_NAME string, 
START_DATE DATE, 
END_DATE DATE, 
DESCRIPTION string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_TOU_ZONES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_TOU_ZONES(
TIME_ZONE_ID int, 
ADMIN_ENTITY_VALUE_ID int, 
TIMEZONE string, 
START_TIME string, 
END_TIME string, 
TIME_ZONE_STATUS string, 
DESCRIPTION string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_UOM;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_UOM(
UOM_ID int, 
UNIT_OF_MEASURE string, 
UOM_CODE string, 
UOM_CLASS string, 
BASE_UOM_FLAG string, 
UOM_TL string, 
DISABLE_DATE DATE, 
DESCRIPTION string, 
LANGUAGE string, 
SOURCE_LANG string, 
ATTRIBUTE_CATEGORY string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATE_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_USERS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_USERS(
USER_ID int, 
USER_NAME string, 
USER_PWD string, 
START_DATE DATE, 
END_DATE DATE, 
SECRET_QUESTION string, 
SECRET_ANSWER string, 
NO_OF_SESSIONS int, 
LOGIN_TIME TIMESTAMP, 
LAST_LOGGED_IN_TIME TIMESTAMP, 
USER_STATUS string, 
EMAIL_ADDRESS string, 
REMARKS string, 
PWD_UPDATE_DATE DATE, 
HIERARCHY_VALUE_ID int, 
HIERARCHY_ID int, 
DESIGNATION_ID int, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE, 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_USER_ROLE;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_USER_ROLE(
USER_ROLE_ID int, 
USER_ID int, 
ROLE_ID int, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_VEE_ALGORITHM_CONFIG;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_VEE_ALGORITHM_CONFIG(
ALG_CONFIG_ID int, 
INACTIVE string, 
CIC string, 
MIC string, 
MI string, 
KVARH string, 
TOU string, 
SPIKE string, 
CZC string, 
DRL string, 
HUSG string, 
LUSG string, 
DIP string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string, 
MIC_KWH_THRESHOLD int, 
MIC_KVAH_THRESHOLD int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_VEE_ALG_FAIL;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_VEE_ALG_FAIL(
VEE_ALG_FAIL_ID int, 
MTR_NO int, 
ALG_CODE string, 
ALG_NAME string, 
FAIL_DATE TIMESTAMP, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_VEE_PARAMETERS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_VEE_PARAMETERS(
VEE_PARA_ID int, 
VEE_PARA_CODE string, 
VEE_PARA_NAME string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_VEE_THRESHOLD;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_VEE_THRESHOLD(
VEE_THRESHOLD_ID int, 
VEE_PARA_ID int, 
CATEGORY_TYPE_ID int, 
MTR_PHASE_ID int, 
MIN_VALUE int, 
MAX_VALUE int, 
MIN_PERCENTAGE int, 
MAX_PERCENTAGE int, 
USER_ID int, 
CHANGE_DATE DATE, 
EFFECTIVE_DATE DATE, 
DESCRIPTION string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_VENDOR;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_VENDOR(
VENDOR_ID int, 
VENDOR_NAME string, 
DESCRIPTION string, 
RECORD_STATUS string, 
CREATED_BY int, 
CREATION_DATE DATE , 
LAST_UPDATED_BY int, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN int, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SS2K5_CHECK_CONSTRAINTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SS2K5_CHECK_CONSTRAINTS(
DB_ID bigint, 
OBJECT_ID bigint, 
PARENT_COLUMN_ID bigint, 
DEFINITION string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SS2K5_COLUMNS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SS2K5_COLUMNS(
DB_ID bigint, 
NAME string, 
RULE_OBJECT_ID bigint, 
COLUMN_ID bigint, 
MAX_LENGTH int, 
PRECISION int, 
SCALE int, 
IS_NULLABLE int, 
USER_TYPE_ID bigint, 
SYSTEM_TYPE_ID int, 
DEFAULT_OBJECT_ID bigint, 
OBJECT_ID bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SS2K5_DATABASES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SS2K5_DATABASES(
DB_ID bigint, 
NAME string, 
DATABASE_ID bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SS2K5_DATABASE_PRINCIPALS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SS2K5_DATABASE_PRINCIPALS(
DB_ID bigint, 
DEFAULT_SCHEMA_NAME string, 
TYPE string, 
PRINCIPAL_ID bigint, 
OWNING_PRINCIPAL_ID bigint, 
NAME string, 
SID BINARY
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SS2K5_DATABASE_ROLE_MEMBERS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SS2K5_DATABASE_ROLE_MEMBERS(
DB_ID bigint, 
MEMBER_PRINCIPAL_ID bigint, 
ROLE_PRINCIPAL_ID bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SS2K5_DEFAULT_CONSTRAINTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SS2K5_DEFAULT_CONSTRAINTS(
DB_ID bigint, 
DEFINITION string, 
OBJECT_ID bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SS2K5_FOREIGN_KEYS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SS2K5_FOREIGN_KEYS(
DB_ID bigint, 
NAME string, 
OBJECT_ID bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SS2K5_FOREIGN_KEY_COLUMNS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SS2K5_FOREIGN_KEY_COLUMNS(
DB_ID bigint, 
CONSTRAINT_COLUMN_ID bigint, 
CONSTRAINT_OBJECT_ID bigint, 
PARENT_OBJECT_ID bigint, 
PARENT_COLUMN_ID bigint, 
REFERENCED_COLUMN_ID bigint, 
REFERENCED_OBJECT_ID bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SS2K5_IDENTITY_COLUMNS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SS2K5_IDENTITY_COLUMNS(
DB_ID int, 
SEED_VALUE int, 
INCREMENT_VALUE int, 
LAST_VALUE int, 
OBJECT_ID int, 
COLUMN_ID int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.SS2K5_INDEXES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SS2K5_INDEXES(
DB_ID bigint, 
OBJECT_ID bigint, 
INDEX_ID bigint, 
NAME string, 
IS_UNIQUE int, 
IS_PRIMARY_KEY int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SS2K5_INDEX_COLUMNS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SS2K5_INDEX_COLUMNS(
DB_ID bigint, 
INDEX_COLUMN_ID bigint, 
OBJECT_ID bigint, 
INDEX_ID bigint, 
COLUMN_ID bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SS2K5_OBJECTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SS2K5_OBJECTS(
DB_ID bigint, 
SCHEMA_ID bigint, 
OBJECT_ID bigint, 
NAME string, 
TYPE string, 
PARENT_OBJECT_ID bigint, 
IS_MS_SHIPPED int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SS2K5_SCHEMAS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SS2K5_SCHEMAS(
DB_ID bigint, 
SCHEMA_ID bigint, 
NAME string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SS2K5_SCHEMATA;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SS2K5_SCHEMATA(
DB_ID bigint, 
SCHEMA_OWNER string, 
SCHEMA_NAME string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




DROP TABLE IF EXISTS mmd.SS2K5_SERVER_PRINCIPALS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SS2K5_SERVER_PRINCIPALS(
DB_ID bigint, 
NAME string, 
SID BINARY, 
TYPE string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SS2K5_SQL_MODULES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SS2K5_SQL_MODULES(
DB_ID bigint, 
DEFINITION string, 
OBJECT_ID bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SS2K5_SYSPROPERTIES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SS2K5_SYSPROPERTIES(
DB_ID int, 
MAJOR_ID int, 
MINOR_ID int, 
NAME string, 
VALUE string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.SS2K5_TABLES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SS2K5_TABLES(
DB_ID bigint, 
NAME string, 
OBJECT_ID bigint, 
SCHEMA_ID bigint, 
TYPE string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.SS2K5_TABLE_PRIVILEGES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SS2K5_TABLE_PRIVILEGES(
DB_ID bigint, 
GRANTOR string, 
TABLE_SCHEMA string, 
TABLE_NAME string, 
PRIVILEGE_TYPE string, 
IS_GRANTABLE string, 
GRANTEE string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SS2K5_TYPES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SS2K5_TYPES(
DB_ID bigint, 
NAME string, 
USER_TYPE_ID bigint, 
SYSTEM_TYPE_ID int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_MIGRLOG;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_MIGRLOG(
SVRID_FK int, 
DBID_GEN_FK int, 
ID int, 
REF_OBJECT_ID int, 
REF_OBJECT_TYPE string, 
LOG_DATE TIMESTAMP, 
SEVERITY int, 
LOGTEXT string, 
PHASE string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_SERVERDETAIL;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SERVERDETAIL(
SVRID int, 
DBURL string, 
DB_NAME string, 
USERNAME string, 
PROJECT_ID int, 
PROJECT_NAME string, 
COMMENTS string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_SS2K5_CHECK_CONSTRAINTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SS2K5_CHECK_CONSTRAINTS(
SVRID_FK int, 
DBID_GEN_FK int, 
OBJECT_ID_GEN int, 
OBJECT_ID int, 
PARENT_COLUMN_ID int, 
DEFINITION string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_SS2K5_COLUMNS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SS2K5_COLUMNS(
SVRID_FK int, 
DBID_GEN_FK int, 
ID_GEN_FK int, 
COLID_GEN int, 
NAME string, 
RULE_OBJECT_ID int, 
COLUMN_ID int, 
MAX_LENGTH int, 
PRECISION int, 
SCALE int, 
IS_NULLABLE int, 
USER_TYPE_ID int, 
SYSTEM_TYPE_ID int, 
DEFAULT_OBJECT_ID int, 
OBJECT_ID int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_SS2K5_DATABASES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SS2K5_DATABASES(
SVRID_FK int, 
DBID_GEN int, 
NAME string, 
DATABASE_ID int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_SS2K5_DB_PRINCIPALS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SS2K5_DB_PRINCIPALS(
SVRID_FK int, 
DBID_GEN_FK int, 
PRINID_GEN int, 
DEFAULT_SCHEMA_NAME string, 
TYPE string, 
PRINCIPAL_ID int, 
OWNING_PRINCIPAL_ID int, 
NAME string, 
SID BINARY
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_SS2K5_DB_ROLE_MEMBERS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SS2K5_DB_ROLE_MEMBERS(
SVRID_FK int, 
DBID_GEN_FK int, 
MEMBER_PRINCIPAL_ID int, 
ROLE_PRINCIPAL_ID int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_SS2K5_DT_CONSTRAINTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SS2K5_DT_CONSTRAINTS(
SVRID_FK int, 
DBID_GEN_FK int, 
OBJID_GEN int, 
DEFINITION string, 
OBJECT_ID int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_SS2K5_FN_KEYS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SS2K5_FN_KEYS(
SVRID_FK int, 
DBID_GEN_FK int, 
OBJECT_ID_GEN int, 
NAME string, 
OBJECT_ID int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_SS2K5_FN_KEY_COLUMNS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SS2K5_FN_KEY_COLUMNS(
SVRID_FK int, 
DBID_GEN_FK int, 
CONSTRAINT_COLUMN_ID int, 
CONSTRAINT_OBJECT_ID int, 
PARENT_OBJECT_ID int, 
PARENT_COLUMN_ID int, 
REFERENCED_COLUMN_ID int, 
REFERENCED_OBJECT_ID int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_SS2K5_IDENTITY_COLUMNS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SS2K5_IDENTITY_COLUMNS(
SVRID_FK int, 
DBID_GEN_FK int, 
OBJECT_ID_GEN int, 
SEED_VALUE int, 
INCREMENT_VALUE int, 
LAST_VALUE int, 
OBJECT_ID int, 
COLUMN_ID int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_SS2K5_INDEXES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SS2K5_INDEXES(
SVRID_FK int, 
DBID_GEN_FK int, 
OBJECT_ID_GEN int, 
OBJECT_ID int, 
INDEX_ID int, 
NAME string, 
IS_UNIQUE int, 
IS_PRIMARY_KEY int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_SS2K5_INDEX_COLUMNS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SS2K5_INDEX_COLUMNS(
SVRID_FK int, 
DBID_GEN_FK int, 
OBJECT_ID_GEN int, 
INDEX_COLUMN_ID int, 
OBJECT_ID int, 
INDEX_ID int, 
COLUMN_ID int, 
IS_DESCENDING_KEY int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_SS2K5_OBJECTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SS2K5_OBJECTS(
SVRID_FK int, 
DBID_GEN_FK int, 
OBJID_GEN int, 
SCHEMA_ID int, 
OBJECT_ID int, 
NAME string, 
TYPE string, 
PARENT_OBJECT_ID int, 
IS_MS_SHIPPED int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_SS2K5_SCHEMAS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SS2K5_SCHEMAS(
SVRID_FK int, 
DBID_GEN_FK int, 
SUID_GEN int, 
SCHEMA_ID int, 
NAME string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_SS2K5_SCHEMATA;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SS2K5_SCHEMATA(
SVRID_FK int, 
DBID_GEN_FK int, 
SUID_GEN int, 
SCHEMA_OWNER string, 
SCHEMA_NAME string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_SS2K5_SERVER_PRINCIPALS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SS2K5_SERVER_PRINCIPALS(
SVRID_FK int, 
DBID_GEN_FK int, 
DB_ID int, 
NAME string, 
SID BINARY, 
TYPE string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_SS2K5_SQL_MODULES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SS2K5_SQL_MODULES(
SVRID_FK int, 
DBID_GEN_FK int, 
OBJID_GEN int, 
DEFINITION string, 
OBJECT_ID int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_SS2K5_SYSPROPERTIES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SS2K5_SYSPROPERTIES(
SVRID_FK int, 
DBID_GEN_FK int, 
CLASS int, 
MAJOR_ID int, 
MINOR_ID int, 
NAME string, 
VALUE string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_SS2K5_TABLES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SS2K5_TABLES(
SVRID_FK int, 
DBID_GEN_FK int, 
OBJID_GEN int, 
SCHEMA_ID_FK int, 
NAME string, 
OBJECT_ID int, 
SCHEMA_ID int, 
TYPE string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_SS2K5_TABLE_PRIVILEGES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SS2K5_TABLE_PRIVILEGES(
SVRID_FK int, 
DBID_GEN_FK int, 
SUID_GEN_FK int, 
GRANTOR string, 
TABLE_SCHEMA string, 
TABLE_NAME string, 
PRIVILEGE_TYPE string, 
IS_GRANTABLE string, 
GRANTEE string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_SS2K5_TYPES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SS2K5_TYPES(
SVRID_FK int, 
DBID_GEN_FK int, 
NAME string, 
USER_TYPE_ID int, 
SYSTEM_TYPE_ID int, 
SCHEMA_ID int, 
MAX_LENGTH int, 
PRECISION int, 
SCALE int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_SYB12_SYSCOLUMNS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SYB12_SYSCOLUMNS(
SVRID_FK int, 
DBID_GEN_FK int, 
ID_GEN_FK int, 
COLID_GEN int, 
ID int, 
DB_int int, 
COLID int, 
STATUS int, 
DB_TYPE int, 
LENGTH int, 
OFFSET int, 
USERTYPE int, 
CDEFAULT int, 
DOMAIN int, 
NAME string, 
PRINTFMT string, 
PREC int, 
SCALE int, 
REMOTE_TYPE int, 
REMOTE_NAME string, 
XSTATUS int, 
XTYPE int, 
XDBID int, 
ACESSRULE int, 
STATUS2 int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_SYB12_SYSCOMMENTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SYB12_SYSCOMMENTS(
SVRID_FK int, 
DBID_GEN_FK int, 
ID_GEN_FK int, 
ID int, 
DB_int int, 
COLID int, 
TEXTTYPE int, 
LANGUAGE int, 
TEXT string, 
COLID2 int, 
STATUS int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_SYB12_SYSCONSTRAINTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SYB12_SYSCONSTRAINTS(
SVRID_FK int, 
DBID_GEN_FK int, 
TABLE_ID_GEN_FK int, 
CONSTRAINT_GEN int, 
COLID int, 
CONSTRID int, 
TABLEID int, 
ERROR int, 
STATUS int, 
SPARE2 int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_SYB12_SYSDATABASES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SYB12_SYSDATABASES(
SVRID_FK int, 
DBID_GEN int, 
NAME string, 
DBID int, 
DB_SUID int, 
STATUS int, 
VERSION int, 
LOGPTR int, 
CRDATE string, 
DUMPTRDATE string, 
STATUS2 int, 
AUDFLAGS int, 
DEFTABAUD int, 
DEFVWAUD int, 
DEFPRAUD int, 
DEF_REMOTE_TYPE int, 
DEF_REMOTE_LOC string, 
STATUS3 int, 
STATUS4 int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_SYB12_SYSINDEXES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SYB12_SYSINDEXES(
SVRID_FK int, 
DBID_GEN_FK int, 
ID_GEN_FK int, 
INDID_GEN int, 
TABLE_ID int, 
INDEX_NAME string, 
INDEX_DESC string, 
INDEX_KEYS string, 
KEYCNT int, 
INDID int, 
STATUS int, 
STATUS2 int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_SYB12_SYSOBJECTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SYB12_SYSOBJECTS(
SVRID_FK int, 
DBID_GEN_FK int, 
OBJID_GEN int, 
SUID_GEN_FK int, 
NAME string, 
ID int, 
DB_UID int, 
DB_TYPE string, 
USERSTAT int, 
SYSSTAT int, 
INDEXDEL int, 
SCHEMATACNT int, 
SYSSTAT2 int, 
CRDATE string, 
EXPDATE string, 
DELTRIG int, 
INSTRIG int, 
UPDTRIG int, 
SELTRIG int, 
CKFIRST int, 
DB_CACHE int, 
AUDFLAGS int, 
OBJSPARE int, 
VERSIONTS BINARY, 
LOGINNAME string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_SYB12_SYSREFERENCES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SYB12_SYSREFERENCES(
SVRID_FK int, 
DBID_GEN_FK int, 
CONSTRAINT_GEN_FK int, 
TABLE_ID_GEN_FK int, 
REF_TABLE_ID_GEN_FK int, 
FRGN_DBID_GEN_FK int, 
PMRY_DBID_GEN_FK int, 
INDEXID int, 
CONSTRID int, 
TABLEID int, 
REFTABID int, 
KEYCNT int, 
STATUS int, 
FRGNDBID int, 
PMRYDBID int, 
SPARE2 int, 
FOKEY1 int, 
FOKEY2 int, 
FOKEY3 int, 
FOKEY4 int, 
FOKEY5 int, 
FOKEY6 int, 
FOKEY7 int, 
FOKEY8 int, 
FOKEY9 int, 
FOKEY10 int, 
FOKEY11 int, 
FOKEY12 int, 
FOKEY13 int, 
FOKEY14 int, 
FOKEY15 int, 
FOKEY16 int, 
REFKEY1 int, 
REFKEY2 int, 
REFKEY3 int, 
REFKEY4 int, 
REFKEY5 int, 
REFKEY6 int, 
REFKEY7 int, 
REFKEY8 int, 
REFKEY9 int, 
REFKEY10 int, 
REFKEY11 int, 
REFKEY12 int, 
REFKEY13 int, 
REFKEY14 int, 
REFKEY15 int, 
REFKEY16 int, 
FRGNDBNAME string, 
PMRYDBNAME string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_SYB12_SYSTYPES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SYB12_SYSTYPES(
SVRID_FK int, 
DBID_GEN_FK int, 
DB_UID int, 
USERTYPE int, 
VARIABLE int, 
ALLOWNULLS int, 
DB_TYPE int, 
LENGTH int, 
TDEFAULT int, 
DOMAIN int, 
NAME string, 
PRINTFMT string, 
PREC int, 
SCALE int, 
IDENT int, 
HEIRARCHY int, 
ACCESSRULE int, 
XTYPEID int, 
VXDBID int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_SYB12_SYSUSERS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_SYB12_SYSUSERS(
SVRID_FK int, 
DBID_GEN_FK int, 
SUID_GEN int, 
GEN_ID_FK int, 
SUID int, 
DB_UID int, 
GID int, 
NAME string, 
ENVIRON string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TERADATA_ALL_RI_PARENTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_ALL_RI_PARENTS(
INDEXNAME string, 
PARENTDB string, 
PARENTTABLE string, 
PARENTKEYCOLUMN string, 
CHILDDB string, 
CHILDTABLE string, 
CHILDKEYCOLUMN string, 
CREATORNAME string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_TERADATA_COLUMNS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_COLUMNS(
MDID int, 
DATABASENAME string, 
TABLENAME string, 
COLUMNNAME string, 
COLUMNFORMAT string, 
COLUMNTITLE string, 
COLUMNTYPE string, 
COLUMNUDTNAME string, 
COLUMNLENGTH bigint, 
DEFAULTVALUE string, 
NULLABLE string, 
COMMENTSTRING string, 
DECIMALTOTALDIGITS bigint, 
DECIMALFRACTIONALDIGITS bigint, 
COLUMNID int, 
UPPERCASEFLAG string, 
COLUMNCONSTRAINT string, 
CONSTRAINTCOUNT bigint, 
CREATORNAME string, 
CHARTYPE bigint, 
IDCOLTYPE string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_TERADATA_DATABASES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_DATABASES(
SVRID int, 
MDID int, 
DATABASENAME string, 
COMMENTSTRING string, 
OWNERNAME string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_TERADATA_FKEYS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_FKEYS(
MDID1 int, 
MDID2 int, 
TABLESCHEMA string, 
TABLENAME string, 
REFTABLESCHEMA string, 
REFTABLENAME string, 
CONSTRAINTNAME string, 
COLUMNNAME string, 
REFCOLUMNNAME string, 
REFKEYNAME string, 
COLUMNSEQ bigint, 
REFERENCEIDX bigint, 
FKEYID bigint, 
PARENTKEYID bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TERADATA_IDXCONSTRAINTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_IDXCONSTRAINTS(
MDID int, 
DATABASENAME string, 
TABLENAME string, 
INDEXNAME string, 
INDEXint bigint, 
CONSTRAINTTYPE string, 
CONSTRAINTTEXT string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TERADATA_INDICES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_INDICES(
MDID int, 
DATABASENAME string, 
TABLENAME string, 
INDEXint bigint, 
INDEXTYPE string, 
UNIQUEFLAG string, 
INDEXNAME string, 
COLUMNNAME string, 
COLUMNPOSITION bigint, 
CREATORNAME string, 
INDEXMODE string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TERADATA_JOININDICES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_JOININDICES(
DATABASENAME string, 
TABLENAME string, 
JOINIDXDATABASENAME string, 
JOINIDXXNAME string, 
INDEXTYPE string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TERADATA_LOG;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_LOG(
LINE int, 
LOGSTRING string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_TERADATA_OFFLINE_CHECK;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_OFFLINE_CHECK(
INDEX int, 
DBNAME string, 
TABNAME string, 
CONSTRAINT_NAME string, 
SEARCH_CONDITION string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TERADATA_OFFLINE_FKEYS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_OFFLINE_FKEYS(
INDEX int, 
DBNAME string, 
TABNAME string, 
REFTABSCHEMA string, 
REFTABNAME string, 
CONSTNAME string, 
COLNAME string, 
REFCOLNAME string, 
TYPE string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TERADATA_OFFLINE_INDC;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_OFFLINE_INDC(
INDEX int, 
NAME string, 
TABLENAME string, 
INDEXNAME string, 
INDEXint int, 
CONSTRAINTTYPE string, 
CONSTRAINTTEXT string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TERADATA_OFFLINE_INDDET;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_OFFLINE_INDDET(
INDEX int, 
DBNAME string, 
TABNAME string, 
INDNAME string, 
COLNAME string, 
COLSEQ int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.STAGE_TERADATA_OFFLINE_INDEXES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_OFFLINE_INDEXES(
INDEX int, 
ID string, 
DBNAME string, 
TABNAME string, 
INDNAME string, 
INDEXTYPE string, 
UNIQUERULE string, 
CREATEUSER string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TERADATA_OFFLINE_PKEYS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_OFFLINE_PKEYS(
INDEX int, 
DBNAME string, 
TABNAME string, 
CONSTNAME string, 
TYPE string, 
COLNAME string, 
COLSEQ int, 
UNIQUEFLAG string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TERADATA_OFFLINE_PROCS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_OFFLINE_PROCS(
INDEX int, 
DBNAME string, 
NAME string, 
ROUTINETYPE string, 
CREATE_TIME string, 
REMARKS string, 
TEXT string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TERADATA_OFFLINE_TABLES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_OFFLINE_TABLES(
INDEX int, 
DBNAME string, 
TABNAME string, 
COLNAME string, 
TYPENAME string, 
CHARTYPE string, 
LENGTH int, 
SCALE int, 
DTOTDIGITS int, 
DFRACDIGITS int, 
NULLS string, 
CHECK string, 
COLUMNUDTNAME string, 
DEFAULTVAL string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TERADATA_OFFLINE_TRIGS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_OFFLINE_TRIGS(
INDEX int, 
TABSCHEMA string, 
TABNAME string, 
OWNER string, 
TRIGNAME string, 
TRIGEVENT string, 
VALID string, 
REMARKS string, 
TEXT string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TERADATA_OFFLINE_VDEFNS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_OFFLINE_VDEFNS(
INDEX int, 
DBNAME string, 
VIEWNAME string, 
TEXT string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TERADATA_OFFLINE_VIEWS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_OFFLINE_VIEWS(
INDEX int, 
DBNAME string, 
VIEWNAME string, 
COLNAME string, 
TYPENAME string, 
LENGTH int, 
SCALE int, 
NULLS string, 
DEFAULTVAL string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TERADATA_PROCEDURES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_PROCEDURES(
MDID int, 
DATABASENAME string, 
PROCNAME string, 
PROCTYPE string, 
REQUESTTEXT string, 
COMMENTSTRING string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TERADATA_SHOWTBLCHECKS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_SHOWTBLCHECKS(
MDID int, 
DATABASENAME string, 
TABLENAME string, 
CHECKNAME string, 
CHECKTYPE string, 
TABLECHECK string, 
COLUMNNAME string, 
CREATORNAME string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TERADATA_TABLES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_TABLES(
MDID int, 
DATABASENAME string, 
TABLENAME string, 
TABLEKIND string, 
CREATORNAME string, 
REQUESTTEXT string, 
COMMENTSTRING string, 
COMMITOPT string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TERADATA_TABLETEXT;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_TABLETEXT(
DATABASENAME string, 
TABLENAME string, 
TABLEKIND string, 
REQUESTTEXT string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TERADATA_TRIGGERS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_TRIGGERS(
MDID int, 
DATABASENAME string, 
SUBJECTTABLEDATABASENAME string, 
TABLENAME string, 
TRIGGERNAME string, 
ENABLEDFLAG string, 
ACTIONTIME string, 
EVENT string, 
KIND string, 
ORDERint bigint, 
TRIGGERCOMMENT string, 
REQUESTTEXT string, 
CREATORNAME string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TERADATA_UDTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TERADATA_UDTS(
MDID int, 
TYPEKIND string, 
TYPENAME string, 
FIELDNAME string, 
FIELDID bigint, 
FIELDTYPE string, 
UDTNAME string, 
CHARTYPE bigint, 
MAXLENGTH bigint, 
DECIMALTOTALDIGITS bigint, 
DECIMALFRACTIONALDIGITS bigint, 
INSTANTIABLE string, 
FINAL string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.STAGE_TRANSLATEDSQL;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.STAGE_TRANSLATEDSQL(
SERVER_ID_FK int, 
DB_ID_FK int, 
SCHEMA_ID_FK int, 
OBJ_ID_FK int, 
NATIVE_SQL string, 
TRANS_SQL string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SYB12_SYSCOLUMNS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SYB12_SYSCOLUMNS(
DB_ID bigint, 
ID bigint, 
DB_int bigint, 
COLID bigint, 
STATUS bigint, 
DB_TYPE bigint, 
LENGTH bigint, 
OFFSET bigint, 
USERTYPE bigint, 
CDEFAULT bigint, 
DOMAIN bigint, 
NAME string, 
PRINTFMT string, 
PREC bigint, 
SCALE bigint, 
REMOTE_TYPE bigint, 
REMOTE_NAME string, 
XSTATUS bigint, 
XTYPE bigint, 
XDBID bigint, 
ACESSRULE bigint, 
STATUS2 bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SYB12_SYSCOMMENTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SYB12_SYSCOMMENTS(
DB_ID bigint, 
ID bigint, 
DB_int bigint, 
COLID bigint, 
TEXTTYPE bigint, 
LANGUAGE bigint, 
TEXT string, 
COLID2 bigint, 
STATUS bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SYB12_SYSCONSTRAINTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SYB12_SYSCONSTRAINTS(
DB_ID bigint, 
TABLE_ID bigint, 
CONSTRAINT_NAME string, 
DB_DEFINITION string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SYB12_SYSDATABASES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SYB12_SYSDATABASES(
DB_ID bigint, 
NAME string, 
DBID bigint, 
DB_SUID bigint, 
STATUS bigint, 
VERSION bigint, 
LOGPTR int, 
CRDATE string, 
DUMPTRDATE string, 
STATUS2 bigint, 
AUDFLAGS bigint, 
DEFTABAUD bigint, 
DEFVWAUD bigint, 
DEFPRAUD bigint, 
DEF_REMOTE_TYPE bigint, 
DEF_REMOTE_LOC string, 
STATUS3 bigint, 
STATUS4 bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




DROP TABLE IF EXISTS mmd.SYB12_SYSINDEXES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SYB12_SYSINDEXES(
DB_ID bigint, 
TABLE_ID bigint, 
INDEX_NAME string, 
INDEX_DESC string, 
INDEX_KEYS string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SYB12_SYSOBJECTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SYB12_SYSOBJECTS(
DB_ID bigint, 
NAME string, 
ID bigint, 
DB_UID bigint, 
DB_TYPE string, 
USERSTAT bigint, 
SYSSTAT bigint, 
INDEXDEL bigint, 
SCHEMATACNT bigint, 
SYSSTAT2 bigint, 
CRDATE string, 
EXPDATE string, 
DELTRIG bigint, 
INSTRIG bigint, 
UPDTRIG bigint, 
SELTRIG bigint, 
CKFIRST bigint, 
DB_CACHE bigint, 
AUDFLAGS bigint, 
OBJSPARE bigint, 
VERSIONTS BINARY, 
LOGINNAME string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.SYB12_SYSTYPES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SYB12_SYSTYPES(
DB_ID bigint, 
DB_UID bigint, 
USERTYPE bigint, 
VARIABLE int, 
ALLOWNULLS int, 
DB_TYPE bigint, 
LENGTH bigint, 
TDEFAULT bigint, 
DOMAIN bigint, 
NAME string, 
PRINTFMT string, 
PREC bigint, 
SCALE bigint, 
IDENT bigint, 
HEIRARCHY bigint, 
ACCESSRULE int, 
XTYPEID int, 
VXDBID int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.SYB12_SYSUSERS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.SYB12_SYSUSERS(
DB_ID bigint, 
SUID bigint, 
DB_UID bigint, 
GID bigint, 
NAME string, 
ENVIRON string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.XXAMI_DEMAND_DASHBOARD_T;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.XXAMI_DEMAND_DASHBOARD_T(
BILLING_PARA_ID int, 
BILL_DATE DATE, 
MTR_SLNO int, 
SANCTIONED_LOAD bigint, 
CONTRACTED_LOAD bigint, 
DEMAND_RESPONSE_LOAD bigint, 
MD_KW int, 
MD_KVA int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


