

DROP TABLE IF EXISTS mmd.EDB$TMP_DEPEND_TBL11001101;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.EDB$TMP_DEPEND_TBL11001101(
schema_name string, 
object_type string, 
object_name string, 
lvl int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.EDB$TMP_MP_MW11001101;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.EDB$TMP_MP_MW11001101(
owner string, 
myview_name string,
query string,
build_mode string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.EDB$TMP_MP_TBL11001101;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.EDB$TMP_MP_TBL11001101(
srno string, 
schema_name string,
schema_validation string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");

    

DROP TABLE IF EXISTS mmd.HIERARCHY_USER;
CREATE TABLE IF NOT EXISTS mmd.HIERARCHY_USER(
hierarchy string,
user_name string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MD_ADDITIONAL_PROPERTIES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_ADDITIONAL_PROPERTIES(
id int, 
CONNECTION_ID_FK bigint, 
REF_ID_FK bigint, 
REF_TYPE string, 
PROPERTY_ORDER bigint, 
PROP_KEY string, 
VALUE string, 
SECURITY_GROUP_ID bigint, 
CREATED_ON DATE, 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


    

DROP TABLE IF EXISTS mmd.MD_APPLICATIONFILES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_APPLICATIONFILES(
ID bigint, 
APPLICATIONS_ID_FK bigint, 
NAME string, 
URI string, 
TYPE string, 
STATE string, 
LANGUAGE string, 
LOC bigint, 
SECURITY_GROUP_ID bigint, 
CREATED_ON DATE, 
CREATED_BY string, 
UPDATED_ON DATE, 
UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");





DROP TABLE IF EXISTS mmd.MD_APPLICATIONS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_APPLICATIONS(
ID bigint, 
NAME string, 
DESCRIPTION string, 
BASE_DIR string, 
OUTPUT_DIR string, 
BACKUP_DIR string, 
INPLACE bigint, 
PROJECT_ID_FK bigint, 
SECURITY_GROUP_ID bigint, 
CREATED_ON DATE, 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");





DROP TABLE IF EXISTS mmd.MD_CATALOGS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_CATALOGS(
ID bigint, 
CONNECTION_ID_FK bigint, 
CATALOG_NAME string, 
DUMMY_FLAG string, 
NATIVE_SQL string, 
NATIVE_KEY string, 
COMMENTS string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");





DROP TABLE IF EXISTS mmd.MD_CODE_REGEX;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_CODE_REGEX(
ID bigint, 
REGEX string, 
DESCRIPTION string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");

    


DROP TABLE IF EXISTS mmd.MD_COLUMNS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_COLUMNS(
ID bigint, 
TABLE_ID_FK bigint, 
COLUMN_NAME string, 
COLUMN_ORDER bigint, 
COLUMN_TYPE string, 
PRECISION bigint, 
SCALE bigint, 
NULLABLE string, 
DEFAULT_VALUE string, 
NATIVE_SQL string, 
NATIVE_KEY string, 
DATATYPE_TRANSFORMED_FLAG string, 
COMMENTS string, 
SECURITY_GROUP_ID bigint , 
CREATED_BY string, 
CREATED_ON DATE , 
LAST_UPDATED_BY string, 
LAST_UPDATED_ON DATE
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




DROP TABLE IF EXISTS mmd.MD_CONNECTIONS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_CONNECTIONS(
ID bigint, 
PROJECT_ID_FK bigint, 
TYPE string, 
HOST string, 
PORT bigint, 
USERNAME string, 
PASSWORD string, 
DBURL string, 
NAME string, 
NATIVE_SQL string, 
STATUS string, 
NUM_CATALOGS bigint, 
NUM_COLUMNS bigint, 
NUM_CONSTRAINTS bigint, 
NUM_GROUPS bigint, 
NUM_ROLES bigint, 
NUM_INDEXES bigint, 
NUM_OTHER_OBJECTS bigint, 
NUM_PACKAGES bigint, 
NUM_PRIVILEGES bigint, 
NUM_SCHEMAS bigint, 
NUM_SEQUENCES bigint, 
NUM_STORED_PROGRAMS bigint, 
NUM_SYNONYMS bigint, 
NUM_TABLES bigint, 
NUM_TABLESPACES bigint, 
NUM_TRIGGERS bigint, 
NUM_USER_DEFINED_DATA_TYPES bigint, 
NUM_USERS bigint, 
NUM_VIEWS bigint, 
COMMENTS string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




DROP TABLE IF EXISTS mmd.MD_CONSTRAINTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_CONSTRAINTS(
ID bigint, 
DELETE_CLAUSE string, 
NAME string, 
CONSTRAINT_TYPE string, 
TABLE_ID_FK bigint, 
REFTABLE_ID_FK bigint, 
CONSTRAINT_TEXT string, 
LANGUAGE string, 
COMMENTS string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MD_CONSTRAINT_DETAILS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_CONSTRAINT_DETAILS(
ID bigint, 
REF_FLAG string, 
CONSTRAINT_ID_FK bigint, 
COLUMN_ID_FK bigint, 
COLUMN_PORTION bigint, 
CONSTRAINT_TEXT string, 
DETAIL_ORDER bigint, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");





DROP TABLE IF EXISTS mmd.MD_DERIVATIVES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_DERIVATIVES(
ID bigint, 
SRC_ID bigint, 
SRC_TYPE string, 
DERIVED_ID bigint, 
DERIVED_TYPE string, 
DERIVED_CONNECTION_ID_FK bigint, 
TRANSFORMED string, 
ORIGINAL_IDENTIFIER string, 
NEW_IDENTIFIER string, 
DERIVED_OBJECT_NAMESPACE string, 
DERIVATIVE_REASON string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string, 
ENABLED string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MD_FILE_ARTIFACTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_FILE_ARTIFACTS(
ID bigint, 
APPLICATIONFILES_ID bigint, 
PATTERN string, 
STRING_FOUND string, 
STRING_REPLACED string, 
TYPE string, 
STATUS string, 
LINE bigint, 
PATTERN_START bigint, 
PATTERN_END bigint, 
DUE_DATE DATE, 
DB_TYPE string, 
CODE_TYPE string, 
DESCRIPTION string, 
PRIORITY bigint, 
SECURITY_GROUP_ID string, 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");

    

DROP TABLE IF EXISTS mmd.MD_GROUPS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_GROUPS(
ID bigint, 
SCHEMA_ID_FK bigint, 
GROUP_NAME string, 
GROUP_FLAG string, 
NATIVE_SQL string, 
NATIVE_KEY string, 
COMMENTS string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




DROP TABLE IF EXISTS mmd.MD_GROUP_MEMBERS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_GROUP_MEMBERS(
ID bigint, 
GROUP_ID_FK bigint, 
USER_ID_FK bigint, 
GROUP_MEMBER_ID_FK bigint, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.MD_GROUP_PRIVILEGES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_GROUP_PRIVILEGES(
ID bigint, 
GROUP_ID_FK bigint, 
PRIVILEGE_ID_FK bigint, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




DROP TABLE IF EXISTS mmd.MD_INDEXES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_INDEXES(
ID bigint, 
INDEX_TYPE string, 
TABLE_ID_FK bigint, 
INDEX_NAME string, 
NATIVE_SQL string, 
NATIVE_KEY string, 
COMMENTS string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");





DROP TABLE IF EXISTS mmd.MD_INDEX_DETAILS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_INDEX_DETAILS(
ID bigint, 
INDEX_ID_FK bigint, 
COLUMN_ID_FK bigint, 
INDEX_PORTION bigint, 
DETAIL_ORDER bigint, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




DROP TABLE IF EXISTS mmd.MD_MIGR_DEPENDENCY;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_MIGR_DEPENDENCY(
ID bigint, 
CONNECTION_ID_FK bigint, 
PARENT_ID bigint, 
CHILD_ID bigint, 
PARENT_OBJECT_TYPE string, 
CHILD_OBJECT_TYPE string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MD_MIGR_PARAMETER;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_MIGR_PARAMETER(
ID bigint, 
CONNECTION_ID_FK bigint, 
OBJECT_ID bigint, 
OBJECT_TYPE string, 
PARAM_EXISTING bigint, 
PARAM_ORDER bigint, 
PARAM_NAME string, 
PARAM_TYPE string, 
PARAM_DATA_TYPE string, 
PERCISION bigint, 
SCALE bigint, 
NULLABLE string, 
DEFAULT_VALUE string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MD_MIGR_WEAKDEP;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_MIGR_WEAKDEP(
ID bigint, 
CONNECTION_ID_FK bigint, 
SCHEMA_ID_FK bigint, 
PARENT_ID bigint, 
CHILD_NAME string, 
PARENT_TYPE string, 
CHILD_TYPE string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MD_NUMROW$SOURCE;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_NUMROW$SOURCE(
NUMROWS bigint, 
NAME string, 
OBJID bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MD_NUMROW$TARGET;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_NUMROW$TARGET(
NUMROWS bigint, 
NAME string, 
OBJID bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");

    

DROP TABLE IF EXISTS mmd.MD_OTHER_OBJECTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_OTHER_OBJECTS(
ID bigint, 
SCHEMA_ID_FK bigint, 
NAME string, 
NATIVE_SQL string, 
NATIVE_KEY string, 
COMMENTS string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MD_PACKAGES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_PACKAGES(
ID bigint, 
SCHEMA_ID_FK bigint, 
NAME string, 
PACKAGE_HEADER string, 
NATIVE_SQL string, 
NATIVE_KEY string, 
LANGUAGE string, 
COMMENTS string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




DROP TABLE IF EXISTS mmd.MD_PARTITIONS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_PARTITIONS(
ID bigint, 
TABLE_ID_FK bigint, 
NATIVE_SQL string, 
PARTITION_EXPRESSION string, 
COMMENTS string, 
SECURITY_GROUP_ID bigint , 
CREATED_BY string, 
CREATED_ON DATE , 
LAST_UPDATED_BY string, 
LAST_UPDATED_ON DATE
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MD_PRIVILEGES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_PRIVILEGES(
ID bigint, 
SCHEMA_ID_FK bigint, 
PRIVILEGE_NAME string, 
PRIVELEGE_OBJECT_ID bigint, 
PRIVELEGEOBJECTTYPE string, 
PRIVELEGE_TYPE string, 
ADMIN_OPTION string, 
NATIVE_SQL string, 
NATIVE_KEY string, 
COMMENTS string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MD_PROJECTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_PROJECTS(
ID bigint, 
PROJECT_NAME string, 
COMMENTS string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MD_REGISTRY;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_REGISTRY(
OBJECT_TYPE string, 
OBJECT_NAME string, 
DESC_OBJECT_NAME string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MD_REPOVERSIONS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_REPOVERSIONS(
REVISION bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MD_SCHEMAS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_SCHEMAS(
ID bigint, 
CATALOG_ID_FK bigint, 
NAME string, 
TYPE string, 
CHARACTER_SET string, 
VERSION_TAG string, 
NATIVE_SQL string, 
NATIVE_KEY string, 
COMMENTS string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MD_SEQUENCES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_SEQUENCES(
ID bigint, 
SCHEMA_ID_FK bigint, 
NAME string, 
SEQ_START bigint, 
INCR bigint , 
NATIVE_SQL string, 
NATIVE_KEY string, 
COMMENTS string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string , 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MD_STORED_PROGRAMS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_STORED_PROGRAMS(
ID bigint, 
SCHEMA_ID_FK bigint, 
PROGRAMTYPE string, 
NAME string, 
PACKAGE_ID_FK bigint, 
NATIVE_SQL string, 
NATIVE_KEY string, 
LANGUAGE string, 
COMMENTS string, 
LINECOUNT bigint, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MD_SYNONYMS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_SYNONYMS(
ID bigint, 
SCHEMA_ID_FK bigint, 
NAME string, 
SYNONYM_FOR_ID bigint, 
FOR_OBJECT_TYPE string, 
PRIVATE_VISIBILITY string, 
NATIVE_SQL string, 
NATIVE_KEY string, 
COMMENTS string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MD_TABLES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_TABLES(
ID bigint, 
SCHEMA_ID_FK bigint, 
TABLE_NAME string, 
NATIVE_SQL string, 
NATIVE_KEY string, 
QUALIFIED_NATIVE_NAME string, 
COMMENTS string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.MD_TABLESPACES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_TABLESPACES(
ID bigint, 
SCHEMA_ID_FK bigint, 
TABLESPACE_NAME string, 
NATIVE_SQL string, 
NATIVE_KEY string, 
COMMENTS string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




DROP TABLE IF EXISTS mmd.MD_TARGET_ALL_ERRORS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_TARGET_ALL_ERRORS(
OWNER string, 
NAME string, 
TYPE string, 
SEQUENCE bigint, 
LINE bigint, 
POSITION bigint, 
TEXT string, 
ATTRIBUTE string, 
MESSAGE_bigint bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




DROP TABLE IF EXISTS mmd.MD_TARGET_ALL_OBJECTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_TARGET_ALL_OBJECTS(
STATUS string, 
OBJECT_NAME string, 
OWNER string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MD_TRIGGERS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_TRIGGERS(
ID bigint, 
TABLE_OR_VIEW_ID_FK bigint, 
TRIGGER_ON_FLAG string, 
TRIGGER_NAME string, 
TRIGGER_TIMING string, 
TRIGGER_OPERATION string, 
TRIGGER_EVENT string, 
NATIVE_SQL string, 
NATIVE_KEY string, 
LANGUAGE string, 
COMMENTS string, 
LINECOUNT bigint, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MD_USERS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_USERS(
ID bigint, 
SCHEMA_ID_FK bigint, 
USERNAME string, 
PASSWORD string, 
NATIVE_SQL string, 
NATIVE_KEY string, 
COMMENTS string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");
    

DROP TABLE IF EXISTS mmd.MD_USER_DEFINED_DATA_TYPES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_USER_DEFINED_DATA_TYPES(
ID bigint, 
SCHEMA_ID_FK bigint, 
DATA_TYPE_NAME string, 
DEFINITION string, 
NATIVE_SQL string, 
NATIVE_KEY string, 
COMMENTS string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");

    

DROP TABLE IF EXISTS mmd.MD_USER_PRIVILEGES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_USER_PRIVILEGES(
ID bigint, 
USER_ID_FK bigint, 
PRIVILEGE_ID_FK bigint, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UDPATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MD_VIEWS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MD_VIEWS(
ID bigint, 
SCHEMA_ID_FK bigint, 
VIEW_NAME string, 
NATIVE_SQL string, 
NATIVE_KEY string, 
LANGUAGE string, 
COMMENTS string, 
LINECOUNT bigint, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MIGRATION_RESERVED_WORDS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MIGRATION_RESERVED_WORDS(
KEYWORD string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");
    

DROP TABLE IF EXISTS mmd.MIGRLOG;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MIGRLOG(
ID bigint, 
PARENT_LOG_ID bigint, 
LOG_DATE TIMESTAMP , 
SEVERITY bigint, 
LOGTEXT string, 
PHASE string, 
REF_OBJECT_ID bigint, 
REF_OBJECT_TYPE string, 
CONNECTION_ID_FK bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");

    

DROP TABLE IF EXISTS mmd.MIGR_DATATYPE_TRANSFORM_MAP;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MIGR_DATATYPE_TRANSFORM_MAP(
ID bigint, 
PROJECT_ID_FK bigint, 
MAP_NAME string, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");

    

DROP TABLE IF EXISTS mmd.MIGR_DATATYPE_TRANSFORM_RULE;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MIGR_DATATYPE_TRANSFORM_RULE(
ID bigint, 
MAP_ID_FK bigint, 
SOURCE_DATA_TYPE_NAME string, 
SOURCE_PRECISION bigint, 
SOURCE_SCALE bigint, 
TARGET_DATA_TYPE_NAME string, 
TARGET_PRECISION bigint, 
TARGET_SCALE bigint, 
SECURITY_GROUP_ID bigint , 
CREATED_ON DATE , 
CREATED_BY string, 
LAST_UPDATED_ON DATE, 
LAST_UPDATED_BY string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");

    

DROP TABLE IF EXISTS mmd.MIGR_GENERATION_ORDER;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MIGR_GENERATION_ORDER(
ID bigint, 
CONNECTION_ID_FK bigint, 
OBJECT_ID bigint, 
OBJECT_TYPE string, 
GENERATION_ORDER bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




DROP TABLE IF EXISTS mmd.MMD_ACCESSORY;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_ACCESSORY(
ID bigint, 
SERIAL_NO string, 
DEVICE_TYPE string, 
MANUFACTURER string, 
ACTIVATED string, 
DEVICE_STATUS string, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE, 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_ADMIN_ENTITIES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_ADMIN_ENTITIES(
ADMIN_ENTITY_ID bigint, 
ADMIN_ENTITY_CODE string, 
ADMIN_ENTITY_NAME string, 
DESCRIPTION string, 
INDEPENDENT string, 
DEPENDENT_ON bigint, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE , 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");





DROP TABLE IF EXISTS mmd.MMD_ADMIN_ENTITY;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_ADMIN_ENTITY(
ADMIN_ENTITY_ID bigint, 
ADMIN_ENTITY_CODE string, 
ADMIN_ENTITY_NAME string, 
DESCRIPTION string, 
INDEPENDENT string, 
DEPENDENT_ON bigint, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE , 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




DROP TABLE IF EXISTS mmd.MMD_ADMIN_ENTITY_VALUES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_ADMIN_ENTITY_VALUES(
ADMIN_ENTITY_VALUE_ID bigint, 
CODE string, 
PARENT_ID bigint, 
ENTITY_ID bigint, 
NAME string, 
DESCRIPTION string, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE , 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");





DROP TABLE IF EXISTS mmd.MMD_ADMIN_VALUES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_ADMIN_VALUES(
ADMIN_ENTITY_VALUE_ID bigint, 
CODE string, 
PARENT_ID bigint, 
ENTITY_ID bigint, 
NAME string, 
DESCRIPTION string, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE , 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");

    


DROP TABLE IF EXISTS mmd.MMD_ALGORITHM;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_ALGORITHM(
ALG_ID bigint, 
ALG_CODE string, 
ALG_NAME string, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE , 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




DROP TABLE IF EXISTS mmd.MMD_ALGORITHM_CONFIG;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_ALGORITHM_CONFIG(
ALG_CONFIG_ID bigint, 
METER_ID bigint, 
MTR_NO string, 
INACTIVE string, 
CIC string, 
MIC string, 
MI string, 
KVARH string, 
TOU string, 
SPIKE string, 
CZC string, 
DRL string, 
HUSG string, 
LUSG string, 
DIP string, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE , 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




DROP TABLE IF EXISTS mmd.MMD_ALGORITHM_INPUTS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_ALGORITHM_INPUTS(
ALG_INPUT_ID bigint, 
ALG_ID bigint, 
FAILURE_TYPE string, 
REQUIRED_EST string, 
REQUIRED_EDIT string, 
NOTIFICATION_REQ string, 
ONSCREEN string, 
SMS string, 
EMAIL string, 
NOTIFY_USER string, 
PERSONAL_MOBILE bigint, 
EMAIL_ID string, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE , 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");

    

DROP TABLE IF EXISTS mmd.MMD_ASSET;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_ASSET(
ID bigint, 
ASSET_NO bigint, 
DTR_ID bigint, 
TYPE_SUPPLY string, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE, 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.MMD_CATEGORY;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_CATEGORY(
CATEGORY_ID bigint, 
CODE string, 
NAME string, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE , 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_CATEGORY_TYPE;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_CATEGORY_TYPE(
CATEGORY_TYPE_ID bigint, 
TYPE string, 
CATEGORY_ID bigint, 
DESCRIPTION string, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE , 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string, 
ABNORMALLY_HIGH bigint, 
ABNORMALLY_LOW bigint, 
HIGH bigint, 
LOW bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.MMD_CATEGORY_TYPES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_CATEGORY_TYPES(
CATEGORY_TYPE_ID bigint, 
SCATCODE string, 
TYPE string, 
TYPE_ID bigint, 
CATEGORY_ID bigint, 
DESCRIPTION string, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE , 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string, 
ABNORMALLY_HIGH bigint, 
ABNORMALLY_LOW bigint, 
HIGH bigint, 
LOW bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_COMM_MEDIA;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_COMM_MEDIA(
ID bigint, 
MEDIA string, 
ADDRESS string, 
PROTOCOL_ID bigint, 
PASSWORD string, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE, 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_CONNECTION_TYPES;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_CONNECTION_TYPES(
MTR_CONN_TYPE_ID bigint, 
MTR_CONN_TYPE string, 
DESCRIPTION string, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE , 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_CONSUMERS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_CONSUMERS(
CONSUMER_ID bigint, 
SCNO string, 
UKSCNO string, 
NAME string, 
ADDRESS1 string, 
ADDRESS2 string, 
ADDRESS3 string, 
ADDRESS4 string, 
MOBILE bigint, 
PHONE bigint, 
EMAIL string, 
CATEGORY_ID bigint, 
PHASE string, 
SANCTIONED_LOAD bigint, 
CONTRACTED_LOAD bigint, 
DEMAND_RESPONSE_LOAD bigint, 
CONNECTED_LOAD bigint, 
LOAD_UNIT string, 
LOAD_TYPE string, 
DTR_ID bigint, 
FEEDER_ID bigint, 
FDTR_ID bigint, 
SUBSTATION_ID bigint, 
AVG_KWH bigint, 
AVG_KVAH bigint, 
ACCOUNT_NO string, 
APPROVEDPOWERFACTOR bigint, 
BILLING_STATUS string, 
ROUTE_ID string, 
BUSINESS_PARTNER string, 
ACCOUNT_STATUS string, 
BILL_ISSUE_FREQ string, 
SUBSCRIPTION_bigint string, 
AGREEMENT_DATE DATE, 
SUPP_RELEASE_DATE DATE, 
ASSET_ID bigint, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE, 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_CONSUMER_HISTORY;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_CONSUMER_HISTORY(
ID bigint, 
CONSUMER_ID bigint, 
OLD_ACCOUNT_NO bigint, 
NAME string, 
EFFECT_DATE DATE, 
FATHER_NAME string, 
ADDRESS string, 
PHONE bigint, 
EMAIL string, 
PHASE string, 
CONTRACTED_LOAD bigint, 
CONNECTED_LOAD bigint, 
LOAD_UNIT bigint, 
CONSUMER_STATUS string, 
PILLAR_NUM bigint, 
BILLING_CYCLE string, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE, 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_DCU;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_DCU(
DCU_ID bigint, 
DCU_MAKE_ID bigint, 
DCU_TYPE_ID bigint, 
PROTOCOL_ID bigint, 
PARENT_ID string, 
IP_ADDRESS string, 
PORT_NO bigint, 
HES_ID bigint, 
FIRMWARE_ID string, 
SIM_ID bigint, 
IMEI_bigint string, 
TRAP_ENABLED string, 
FEP_ID string, 
GPSLOC_ID bigint, 
DTR_ID bigint, 
STATUS_ID bigint, 
COMM_MEDIA_ID bigint, 
MAC_ADDRESS string, 
MPERIOD TIMESTAMP , 
TRANSFORMERMODE_ID string, 
DCU_MODEL string, 
DCU_SLNO string, 
OBIS_LIST_VERSION string, 
HARDWARE_VERSION string, 
FAILURE_DATE DATE, 
INSTALLED_DATE DATE, 
COMMISONED_DATE DATE, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE, 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




DROP TABLE IF EXISTS mmd.MMD_DCU_HISTORY;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_DCU_HISTORY(
DCU_HIS_ID bigint, 
DCU_STATUS string, 
CHANGE_REASON string, 
OLD_DCU_SLNO string, 
FAILURE_DATE DATE, 
FIRMWARE_ID string, 
DESCRIPTION string, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE , 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_DESIGNATION;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_DESIGNATION(
DESIGNATION_ID bigint, 
DESIGNATION_CODE string, 
DESCRIPTION string, 
REPORTING_TO bigint, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE , 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



DROP TABLE IF EXISTS mmd.MMD_DTRS;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_DTRS(
DTR_ID bigint, 
CODE string, 
NAME string, 
CAPACITY string, 
FEEDER_ID bigint, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE, 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


DROP TABLE IF EXISTS mmd.MMD_EMPLOYEE;
CREATE EXTERNAL TABLE IF NOT EXISTS mmd.MMD_EMPLOYEE(
EMP_ID bigint, 
EMP_CODE string, 
DESIGNATION_ID bigint, 
USER_ID bigint, 
FIRST_NAME string, 
MIDDLE_NAME string, 
LAST_NAME string, 
FATHER_SPOUSE_NAME string, 
DOOR_NO string, 
STREET string, 
AREA string, 
CITY string, 
ZIPCODE string, 
PHONE1 bigint, 
PHONE2 bigint, 
EMAIL_ADDRESS string, 
DOB DATE, 
GENDER string, 
HIRE_DATE DATE, 
JOINING_DATE DATE, 
RETIRED_DATE DATE, 
TERMINATED_DATE DATE, 
LATEST_DESIG_ID bigint, 
REPORTING_TO_ID bigint, 
REPORTING_OFFICE_ID bigint, 
EMP_STATUS string, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE , 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE , 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


