CREATE EXTERNAL TABLE IF NOT EXISTS MPM.BILLING_PARAMETERS_22_03(
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
BILLING_DATE TIMESTAMP, 
SYS_PWR_FACT_BILLING_PERIOD bigint, 
EXTRA_COL_KWH bigint, 
CUM_ENG_KWH bigint, 
CUM_ENG_KWH_TZ_1 bigint, 
CUM_ENG_KWH_TZ_2 bigint, 
CUM_ENG_KWH_TZ_3 bigint, 
CUM_ENG_KWH_TZ_4 bigint, 
CUM_ENG_KWH_TZ_5 bigint, 
CUM_ENG_KWH_TZ_6 bigint, 
CUM_ENG_KWH_TZ_7 bigint, 
CUM_ENG_KWH_TZ_8 bigint, 
CUM_ENG_KVARH_LAG bigint, 
CUM_ENG_KVARH_LEAD bigint, 
EXTRA_COL_KVAH bigint, 
CUM_ENG_KVAH bigint, 
CUM_ENG_KVAH_TZ_1 bigint, 
CUM_ENG_KVAH_TZ_2 bigint, 
CUM_ENG_KVAH_TZ_3 bigint, 
CUM_ENG_KVAH_TZ_4 bigint, 
CUM_ENG_KVAH_TZ_5 bigint, 
CUM_ENG_KVAH_TZ_6 bigint, 
CUM_ENG_KVAH_TZ_7 bigint, 
CUM_ENG_KVAH_TZ_8 bigint, 
MD_KW bigint, 
MD_KW_TZ_1 bigint, 
MD_KW_TZ_2 bigint, 
MD_KW_TZ_3 bigint, 
MD_KW_TZ_4 bigint, 
MD_KW_TZ_5 bigint, 
MD_KW_TZ_6 bigint, 
MD_KW_TZ_7 bigint, 
MD_KW_TZ_8 bigint, 
MD_KVA bigint, 
MD_KVA_TZ_1 bigint, 
MD_KVA_TZ_2 bigint, 
MD_KVA_TZ_3 bigint, 
MD_KVA_TZ_4 bigint, 
MD_KVA_TZ_5 bigint, 
MD_KVA_TZ_6 bigint, 
MD_KVA_TZ_7 bigint, 
MD_KVA_TZ_8 bigint, 
CUM_ENG_KWH_EXP bigint, 
CUM_ENG_KVAH_EXP bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



CREATE EXTERNAL TABLE IF NOT EXISTS DAILY_LOAD_ASSET_PARAMETERS(
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
BATTERY_VOLTAGE bigint, 
GSM_FIELD_STRENGTH bigint, 
TELEPHONE_NO bigint, 
CURRENT_IR bigint, 
CURRENT_IY bigint, 
CURRENT_IB bigint, 
VOLTAGE_VRN bigint, 
VOLTAGE_VYN bigint, 
VOLTAGE_VBN bigint, 
BLOCK_ENERGY_KWH_IMP bigint, 
BLOCK_ENERGY_KWH_EXP bigint, 
BLOCK_ENERGY_KVARH_Q1 bigint, 
BLOCK_ENERGY_KVARH_Q2 bigint, 
BLOCK_ENERGY_KVARH_Q3 bigint, 
BLOCK_ENERGY_KVARH_Q4 bigint, 
BLOCK_ENERGY_KVAH_IMP bigint, 
BLOCK_ENERGY_KVAH_EXP bigint, 
REAL_TIME_CLOCK_DATE_TI TIMESTAMP, 
CUM_ENERGY_KWH_IMP bigint, 
CUM_ENERGY_KWH_EXP bigint, 
CUM_ENERGY_KVAH_IMP bigint, 
CUM_ENERGY_KVAH_EXP bigint, 
REACTIVE_ENG_HIGH bigint, 
REACTIVE_ENG_LOW bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint, 
PF bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


CREATE EXTERNAL TABLE IF NOT EXISTS DAILY_LOAD_FACTOR_PARAMETERS
(
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
BATTERY_VOLTAGE bigint, 
GSM_FIELD_STRENGTH bigint, 
TELEPHONE_NO bigint, 
CURRENT_IR bigint, 
CURRENT_IY bigint, 
CURRENT_IB bigint, 
VOLTAGE_VRN bigint, 
VOLTAGE_VYN bigint, 
VOLTAGE_VBN bigint, 
BLOCK_ENERGY_KWH_IMP bigint, 
BLOCK_ENERGY_KWH_EXP bigint, 
BLOCK_ENERGY_KVARH_Q1 bigint, 
BLOCK_ENERGY_KVARH_Q2 bigint, 
BLOCK_ENERGY_KVARH_Q3 bigint, 
BLOCK_ENERGY_KVARH_Q4 bigint, 
BLOCK_ENERGY_KVAH_IMP bigint, 
BLOCK_ENERGY_KVAH_EXP bigint, 
REAL_TIME_CLOCK_DATE_TI TIMESTAMP, 
CUM_ENERGY_KWH_IMP bigint, 
CUM_ENERGY_KWH_EXP bigint, 
CUM_ENERGY_KVAH_IMP bigint, 
CUM_ENERGY_KVAH_EXP bigint, 
REACTIVE_ENG_HIGH bigint, 
REACTIVE_ENG_LOW bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint, 
PF bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


CREATE EXTERNAL TABLE IF NOT EXISTS DAILY_LOAD_PARAMETERS_22_03(
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
BATTERY_VOLTAGE bigint, 
GSM_FIELD_STRENGTH bigint, 
TELEPHONE_NO bigint, 
CURRENT_IR bigint, 
CURRENT_IY bigint, 
CURRENT_IB bigint, 
VOLTAGE_VRN bigint, 
VOLTAGE_VYN bigint, 
VOLTAGE_VBN bigint, 
BLOCK_ENERGY_KWH_IMP bigint, 
BLOCK_ENERGY_KWH_EXP bigint, 
BLOCK_ENERGY_KVARH_Q1 bigint, 
BLOCK_ENERGY_KVARH_Q2 bigint, 
BLOCK_ENERGY_KVARH_Q3 bigint, 
BLOCK_ENERGY_KVARH_Q4 bigint, 
BLOCK_ENERGY_KVAH_IMP bigint, 
BLOCK_ENERGY_KVAH_EXP bigint, 
REAL_TIME_CLOCK_DATE_TI TIMESTAMP, 
CUM_ENERGY_KWH_IMP bigint, 
CUM_ENERGY_KWH_EXP bigint, 
CUM_ENERGY_KVAH_IMP bigint, 
CUM_ENERGY_KVAH_EXP bigint, 
REACTIVE_ENG_HIGH bigint, 
REACTIVE_ENG_LOW bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint, 
PF bigint, 
REF_KWH bigint, 
BLOCK_ENERGY_KWH_IMP_DUMMY bigint, 
BLOCK_ENERGY_KVAH_IMP_DUMMY bigint, 
REF_KVAH bigint, 
VEE_STATUS_MIC bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


CREATE EXTERNAL TABLE IF NOT EXISTS DAILY_LOAD_PARAMETERS_ERR(
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
BATTERY_VOLTAGE bigint, 
GSM_FIELD_STRENGTH bigint, 
TELEPHONE_NO bigint, 
CURRENT_IR bigint, 
CURRENT_IY bigint, 
CURRENT_IB bigint, 
VOLTAGE_VRN bigint, 
VOLTAGE_VYN bigint, 
VOLTAGE_VBN bigint, 
BLOCK_ENERGY_KWH_IMP bigint, 
BLOCK_ENERGY_KWH_EXP bigint, 
BLOCK_ENERGY_KVARH_Q1 bigint, 
BLOCK_ENERGY_KVARH_Q2 bigint, 
BLOCK_ENERGY_KVARH_Q3 bigint, 
BLOCK_ENERGY_KVARH_Q4 bigint, 
BLOCK_ENERGY_KVAH_IMP bigint, 
BLOCK_ENERGY_KVAH_EXP bigint, 
REAL_TIME_CLOCK_DATE_TI TIMESTAMP, 
CUM_ENERGY_KWH_IMP bigint, 
CUM_ENERGY_KWH_EXP bigint, 
CUM_ENERGY_KVAH_IMP bigint, 
CUM_ENERGY_KVAH_EXP bigint, 
REACTIVE_ENG_HIGH bigint, 
REACTIVE_ENG_LOW bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint, 
PF bigint, 
REF_KWH bigint, 
BLOCK_ENERGY_KWH_IMP_DUMMY bigint, 
BLOCK_ENERGY_KVAH_IMP_DUMMY bigint, 
REF_KVAH bigint, 
STAT bigint, 
MTR_IDNT_STAT string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



CREATE EXTERNAL TABLE IF NOT EXISTS DAILY_LOAD_PARAMETERS_RAW(
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
BATTERY_VOLTAGE bigint, 
GSM_FIELD_STRENGTH bigint, 
TELEPHONE_NO bigint, 
CURRENT_IR bigint, 
CURRENT_IY bigint, 
CURRENT_IB bigint, 
VOLTAGE_VRN bigint, 
VOLTAGE_VYN bigint, 
VOLTAGE_VBN bigint, 
BLOCK_ENERGY_KWH_IMP bigint, 
BLOCK_ENERGY_KWH_EXP bigint, 
BLOCK_ENERGY_KVARH_Q1 bigint, 
BLOCK_ENERGY_KVARH_Q2 bigint, 
BLOCK_ENERGY_KVARH_Q3 bigint, 
BLOCK_ENERGY_KVARH_Q4 bigint, 
BLOCK_ENERGY_KVAH_IMP bigint, 
BLOCK_ENERGY_KVAH_EXP bigint, 
REAL_TIME_CLOCK_DATE_TI TIMESTAMP, 
CUM_ENERGY_KWH_IMP bigint, 
CUM_ENERGY_KWH_EXP bigint, 
CUM_ENERGY_KVAH_IMP bigint, 
CUM_ENERGY_KVAH_EXP bigint, 
REACTIVE_ENG_HIGH bigint, 
REACTIVE_ENG_LOW bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint, 
PF bigint, 
REF_KWH bigint, 
BLOCK_ENERGY_KWH_IMP_DUMMY bigint, 
BLOCK_ENERGY_KVAH_IMP_DUMMY bigint, 
REF_KVAH bigint, 
STAT bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




CREATE EXTERNAL TABLE IF NOT EXISTS INSTA_PARA_DUMMY_02_03_18(
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
CURRENT_IR bigint, 
CURRENT_IY bigint, 
CURRENT_IB bigint, 
VOLTAGE_VRN bigint, 
VOLTAGE_VYN bigint, 
VOLTAGE_VBN bigint, 
SIGNED_PWR_FACT_R_PH bigint, 
SIGNED_PWR_FACT_Y_PH bigint, 
SIGNED_PWR_FACT_B_PH bigint, 
SIGNED_PWR_FACT_PF bigint, 
FREQUENCY bigint, 
APPARENT_PWR_KVA bigint, 
SIGNED_ACTIVE_PWR_KW bigint, 
SIGNED_RECTIVE_PWR_KVAR bigint, 
CUM_PROGRAM_COUNT bigint, 
CUM_BILLING_COUNT bigint, 
CUM_ENG_KVAH_IMP bigint, 
CUM_ENG_KWH_IMP bigint, 
CUM_ENG_KWH_EXP bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint, 
CUM_ENG_KVAH_EXP bigint, 
MAX_DEMAND_KW_IMP bigint, 
MAX_DEMAND_KVA_IMP bigint, 
CUM_TAMPER_COUNT bigint, 
NUM_PWR_FAILURE bigint, 
CUM_PWR_OFF_DUR bigint, 
BILLING_DATE TIMESTAMP
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




CREATE EXTERNAL TABLE IF NOT EXISTS MPM_BILLING_PARAMETERS(
BILLING_PARA_ID bigint, 
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
BILLING_DATE TIMESTAMP, 
SYS_PWR_FACT_BILLING_PERIOD bigint, 
CUM_ENG_KWH bigint, 
CUM_ENG_KWH_TZ_1 bigint, 
CUM_ENG_KWH_TZ_2 bigint, 
CUM_ENG_KWH_TZ_3 bigint, 
CUM_ENG_KWH_TZ_4 bigint, 
CUM_ENG_KWH_TZ_5 bigint, 
CUM_ENG_KWH_TZ_6 bigint, 
CUM_ENG_KWH_TZ_7 bigint, 
CUM_ENG_KWH_TZ_8 bigint, 
CUM_ENG_KVARH_LAG bigint, 
CUM_ENG_KVARH_LEAD bigint, 
CUM_ENG_KVAH bigint, 
CUM_ENG_KVAH_TZ_1 bigint, 
CUM_ENG_KVAH_TZ_2 bigint, 
CUM_ENG_KVAH_TZ_3 bigint, 
CUM_ENG_KVAH_TZ_4 bigint, 
CUM_ENG_KVAH_TZ_5 bigint, 
CUM_ENG_KVAH_TZ_6 bigint, 
CUM_ENG_KVAH_TZ_7 bigint, 
CUM_ENG_KVAH_TZ_8 bigint, 
MD_KW bigint, 
MD_KW_TZ_1 bigint, 
MD_KW_TZ_2 bigint, 
MD_KW_TZ_3 bigint, 
MD_KW_TZ_4 bigint, 
MD_KW_TZ_5 bigint, 
MD_KW_TZ_6 bigint, 
MD_KW_TZ_7 bigint, 
MD_KW_TZ_8 bigint, 
MD_KVA bigint, 
MD_KVA_TZ_1 bigint, 
MD_KVA_TZ_2 bigint, 
MD_KVA_TZ_3 bigint, 
MD_KVA_TZ_4 bigint, 
MD_KVA_TZ_5 bigint, 
MD_KVA_TZ_6 bigint, 
MD_KVA_TZ_7 bigint, 
MD_KVA_TZ_8 bigint, 
CUM_ENG_KWH_EXP bigint, 
CUM_ENG_KVAH_EXP bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint, 
RECORD_VEE_STATUS string, 
EDITED_BY string, 
EDITED_DATE TIMESTAMP, 
EDITED_REASON string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




CREATE EXTERNAL TABLE IF NOT EXISTS MPM_BILLING_PARA_XML(
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
BILLING_DATE TIMESTAMP, 
SYS_PWR_FACT_BILLING_PERIOD bigint, 
CUM_ENG_KWH bigint, 
CUM_ENG_KWH_TZ_1 bigint, 
CUM_ENG_KWH_TZ_2 bigint, 
CUM_ENG_KWH_TZ_3 bigint, 
CUM_ENG_KWH_TZ_4 bigint, 
CUM_ENG_KWH_TZ_5 bigint, 
CUM_ENG_KWH_TZ_6 bigint, 
CUM_ENG_KWH_TZ_7 bigint, 
CUM_ENG_KWH_TZ_8 bigint, 
CUM_ENG_KVARH_LAG bigint, 
CUM_ENG_KVARH_LEAD bigint, 
CUM_ENG_KVAH bigint, 
CUM_ENG_KVAH_TZ_1 bigint, 
CUM_ENG_KVAH_TZ_2 bigint, 
CUM_ENG_KVAH_TZ_3 bigint, 
CUM_ENG_KVAH_TZ_4 bigint, 
CUM_ENG_KVAH_TZ_5 bigint, 
CUM_ENG_KVAH_TZ_6 bigint, 
CUM_ENG_KVAH_TZ_7 bigint, 
CUM_ENG_KVAH_TZ_8 bigint, 
MD_KW bigint, 
MD_KW_TZ_1 bigint, 
MD_KW_TZ_2 bigint, 
MD_KW_TZ_3 bigint, 
MD_KW_TZ_4 bigint, 
MD_KW_TZ_5 bigint, 
MD_KW_TZ_6 bigint, 
MD_KW_TZ_7 bigint, 
MD_KW_TZ_8 bigint, 
MD_KVA bigint, 
MD_KVA_TZ_1 bigint, 
MD_KVA_TZ_2 bigint, 
MD_KVA_TZ_3 bigint, 
MD_KVA_TZ_4 bigint, 
MD_KVA_TZ_5 bigint, 
MD_KVA_TZ_6 bigint, 
MD_KVA_TZ_7 bigint, 
MD_KVA_TZ_8 bigint, 
CUM_ENG_KWH_EXP bigint, 
CUM_ENG_KVAH_EXP bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




CREATE EXTERNAL TABLE IF NOT EXISTS DAILY_LOAD_PARAMETERS_ERR(
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
BILLING_DATE TIMESTAMP, 
SYS_PWR_FACT_BILLING_PERIOD bigint, 
CUM_ENG_KWH bigint, 
CUM_ENG_KWH_TZ_1 bigint, 
CUM_ENG_KWH_TZ_2 bigint, 
CUM_ENG_KWH_TZ_3 bigint, 
CUM_ENG_KWH_TZ_4 bigint, 
CUM_ENG_KWH_TZ_5 bigint, 
CUM_ENG_KWH_TZ_6 bigint, 
CUM_ENG_KWH_TZ_7 bigint, 
CUM_ENG_KWH_TZ_8 bigint, 
CUM_ENG_KVARH_LAG bigint, 
CUM_ENG_KVARH_LEAD bigint, 
CUM_ENG_KVAH bigint, 
CUM_ENG_KVAH_TZ_1 bigint, 
CUM_ENG_KVAH_TZ_2 bigint, 
CUM_ENG_KVAH_TZ_3 bigint, 
CUM_ENG_KVAH_TZ_4 bigint, 
CUM_ENG_KVAH_TZ_5 bigint, 
CUM_ENG_KVAH_TZ_6 bigint, 
CUM_ENG_KVAH_TZ_7 bigint, 
CUM_ENG_KVAH_TZ_8 bigint, 
MD_KW bigint, 
MD_KW_TZ_1 bigint, 
MD_KW_TZ_2 bigint, 
MD_KW_TZ_3 bigint, 
MD_KW_TZ_4 bigint, 
MD_KW_TZ_5 bigint, 
MD_KW_TZ_6 bigint, 
MD_KW_TZ_7 bigint, 
MD_KW_TZ_8 bigint, 
MD_KVA bigint, 
MD_KVA_TZ_1 bigint, 
MD_KVA_TZ_2 bigint, 
MD_KVA_TZ_3 bigint, 
MD_KVA_TZ_4 bigint, 
MD_KVA_TZ_5 bigint, 
MD_KVA_TZ_6 bigint, 
MD_KVA_TZ_7 bigint, 
MD_KVA_TZ_8 bigint, 
CUM_ENG_KWH_EXP bigint, 
CUM_ENG_KVAH_EXP bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");





CREATE EXTERNAL TABLE IF NOT EXISTS MPM_BILL_PARA_DUMMY(
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
BILLING_DATE TIMESTAMP, 
SYS_PWR_FACT_BILLING_PERIOD bigint, 
CUM_KVAH_TZ_1 bigint, 
CUM_KVAH_TZ_2 bigint, 
CUM_KVAH_TZ_3 bigint, 
CUM_KVAH_TZ_4 bigint, 
CUM_KVAH_TZ_5 bigint, 
CUM_KVAH_TZ_6 bigint, 
CUM_KVAH_TZ_7 bigint, 
CUM_KVAH_TZ_8 bigint, 
CUM_KVAH bigint, 
CUM_KWH_TZ_1 bigint, 
CUM_KWH_TZ_2 bigint, 
CUM_KWH_TZ_3 bigint, 
CUM_KWH_TZ_4 bigint, 
CUM_KWH_TZ_5 bigint, 
CUM_KWH_TZ_6 bigint, 
CUM_KWH_TZ_7 bigint, 
CUM_KWH_TZ_8 bigint, 
CUM_KWH bigint, 
CUM_KVARH_LEAD bigint, 
MD_KVA bigint, 
MD_KVA_TZ_1 bigint, 
MD_KVA_TZ_2 bigint, 
MD_KVA_TZ_3 bigint, 
MD_KVA_TZ_4 bigint, 
MD_KVA_TZ_5 bigint, 
MD_KVA_TZ_6 bigint, 
MD_KVA_TZ_7 bigint, 
MD_KVA_TZ_8 bigint, 
MD_KW bigint, 
MD_KW_TZ_1 bigint, 
MD_KW_TZ_2 bigint, 
MD_KW_TZ_3 bigint, 
MD_KW_TZ_4 bigint, 
MD_KW_TZ_5 bigint, 
MD_KW_TZ_6 bigint, 
MD_KW_TZ_7 bigint, 
MD_KW_TZ_8 bigint, 
CUM_ENG_KVARH_LAG bigint, 
CUM_ENG_KWH_EXP bigint, 
CUM_ENG_KVAH_EXP bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



CREATE EXTERNAL TABLE IF NOT EXISTS MPM_DAILY_CON_DUMMY
(
MTR_NO string, 
CONSUMPTION_DATE TIMESTAMP, 
CONSUMPTION bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




CREATE EXTERNAL TABLE IF NOT EXISTS MPM_DAILY_LOAD_PARA(
DAILY_LOAD_PARA_ID bigint, 
MTR_NO bigint, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
BATTERY_VOLTAGE bigint, 
GSM_FIELD_STRENGTH bigint, 
TELEPHONE_NO bigint, 
CURRENT_IR bigint, 
CURRENT_IY bigint, 
CURRENT_IB bigint, 
VOLTAGE_VRN bigint, 
VOLTAGE_VYN bigint, 
VOLTAGE_VBN bigint, 
BLOCK_ENERGY_KWH_IMP bigint, 
BLOCK_ENERGY_KWH_EXP bigint, 
BLOCK_ENERGY_KVARH_Q1 bigint, 
BLOCK_ENERGY_KVARH_Q2 bigint, 
BLOCK_ENERGY_KVARH_Q3 bigint, 
BLOCK_ENERGY_KVARH_Q4 bigint, 
BLOCK_ENERGY_KVAH_IMP bigint, 
BLOCK_ENERGY_KVAH_EXP bigint, 
REAL_TIME_CLOCK_DATE_TI TIMESTAMP, 
CUM_ENERGY_KWH_IMP bigint, 
CUM_ENERGY_KWH_EXP bigint, 
CUM_ENERGY_KVAH_IMP bigint, 
CUM_ENERGY_KVAH_EXP bigint, 
REACTIVE_ENG_HIGH bigint, 
REACTIVE_ENG_LOW bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE, 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string, 
RECORD_VEE_STATUS string, 
EDITED_BY string, 
EDITED_DATE TIMESTAMP, 
EDITED_REASON string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




CREATE EXTERNAL TABLE IF NOT EXISTS MPM_DAILY_LOAD_PARAMETERS
(
DAILY_LOAD_PARA_ID bigint, 
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
BATTERY_VOLTAGE bigint, 
GSM_FIELD_STRENGTH bigint, 
TELEPHONE_NO bigint, 
CURRENT_IR bigint, 
CURRENT_IY bigint, 
CURRENT_IB bigint, 
VOLTAGE_VRN bigint, 
VOLTAGE_VYN bigint, 
VOLTAGE_VBN bigint, 
BLOCK_ENERGY_KWH_IMP bigint, 
BLOCK_ENERGY_KWH_EXP bigint, 
BLOCK_ENERGY_KVARH_Q1 bigint, 
BLOCK_ENERGY_KVARH_Q2 bigint, 
BLOCK_ENERGY_KVARH_Q3 bigint, 
BLOCK_ENERGY_KVARH_Q4 bigint, 
BLOCK_ENERGY_KVAH_IMP bigint, 
BLOCK_ENERGY_KVAH_EXP bigint, 
REAL_TIME_CLOCK_DATE_TI TIMESTAMP, 
CUM_ENERGY_KWH_IMP bigint, 
CUM_ENERGY_KWH_EXP bigint, 
CUM_ENERGY_KVAH_IMP bigint, 
CUM_ENERGY_KVAH_EXP bigint, 
REACTIVE_ENG_HIGH bigint, 
REACTIVE_ENG_LOW bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint, 
RECORD_VEE_STATUS string, 
EDITED_BY string, 
EDITED_DATE TIMESTAMP, 
EDITED_REASON string, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE, 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




CREATE EXTERNAL TABLE IF NOT EXISTS MPM_DAILY_LOAD_PARA_DUMMY_D(
DAILY_LOAD_PARA_ID bigint, 
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
BATTERY_VOLTAGE bigint, 
GSM_FIELD_STRENGTH bigint, 
TELEPHONE_NO bigint, 
CURRENT_IR bigint, 
CURRENT_IY bigint, 
CURRENT_IB bigint, 
VOLTAGE_VRN bigint, 
VOLTAGE_VYN bigint, 
VOLTAGE_VBN bigint, 
BLOCK_ENERGY_KWH_IMP bigint, 
BLOCK_ENERGY_KWH_EXP bigint, 
BLOCK_ENERGY_KVARH_Q1 bigint, 
BLOCK_ENERGY_KVARH_Q2 bigint, 
BLOCK_ENERGY_KVARH_Q3 bigint, 
BLOCK_ENERGY_KVARH_Q4 bigint, 
BLOCK_ENERGY_KVAH_IMP bigint, 
BLOCK_ENERGY_KVAH_EXP bigint, 
REAL_TIME_CLOCK_DATE_TI TIMESTAMP, 
CUM_ENERGY_KWH_IMP bigint, 
CUM_ENERGY_KWH_EXP bigint, 
CUM_ENERGY_KVAH_IMP bigint, 
CUM_ENERGY_KVAH_EXP bigint, 
REACTIVE_ENG_HIGH bigint, 
REACTIVE_ENG_LOW bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




CREATE EXTERNAL TABLE IF NOT EXISTS MPM_DAILY_LOAD_PARA_XML(
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
BATTERY_VOLTAGE bigint, 
GSM_FIELD_STRENGTH bigint, 
TELEPHONE_NO bigint, 
CURRENT_IR bigint, 
CURRENT_IY bigint, 
CURRENT_IB bigint, 
VOLTAGE_VRN bigint, 
VOLTAGE_VYN bigint, 
VOLTAGE_VBN bigint, 
BLOCK_ENERGY_KWH_IMP bigint, 
BLOCK_ENERGY_KWH_EXP bigint, 
BLOCK_ENERGY_KVARH_Q1 bigint, 
BLOCK_ENERGY_KVARH_Q2 bigint, 
BLOCK_ENERGY_KVARH_Q3 bigint, 
BLOCK_ENERGY_KVARH_Q4 bigint, 
BLOCK_ENERGY_KVAH_IMP bigint, 
BLOCK_ENERGY_KVAH_EXP bigint, 
CUM_ENERGY_KWH_IMP bigint, 
CUM_ENERGY_KWH_EXP bigint, 
CUM_ENERGY_KVAH_IMP bigint, 
CUM_ENERGY_KVAH_EXP bigint, 
REACTIVE_ENG_HIGH bigint, 
REACTIVE_ENG_LOW bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint, 
RECORD_VEE_STATUS string, 
CUM_POWER_OFF_DURATION_MINS bigint, 
NUM_OF_POWER_FAILURES bigint, 
THRESHOLD_LIMIT_OF_VOLTAGE_SAG bigint, 
TOT_HARMONIC_ACT_POWER_RPH bigint, 
TOT_HARMONIC_ACT_POWER_YPH bigint, 
TOT_HARMONIC_ACT_POWER_BPH bigint, 
TOT_HARMONIC_REACT_POWER_RPH bigint, 
TOT_HARMONIC_REACT_POWER_YPH bigint, 
TOT_HARMONIC_REACT_POWER_BPH bigint, 
TERMINAL_COVER_REMOVE_CNT bigint, 
MTR_INT_OPERATING_STATUS string, 
THRESHOLD_LIMIT_OF_CUR_PEAK bigint, 
THRESHOLD_LIMIT_OF_VOL_PEAK bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




CREATE EXTERNAL TABLE IF NOT EXISTS MPM_DAILY_LOAD_PARA_XML2(
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
BATTERY_VOLTAGE bigint, 
GSM_FIELD_STRENGTH bigint, 
TELEPHONE_NO bigint, 
CURRENT_IR bigint, 
CURRENT_IY bigint, 
CURRENT_IB bigint, 
VOLTAGE_VRN bigint, 
VOLTAGE_VYN bigint, 
VOLTAGE_VBN bigint, 
BLOCK_ENERGY_KWH_IMP bigint, 
BLOCK_ENERGY_KWH_EXP bigint, 
BLOCK_ENERGY_KVARH_Q1 bigint, 
BLOCK_ENERGY_KVARH_Q2 bigint, 
BLOCK_ENERGY_KVARH_Q3 bigint, 
BLOCK_ENERGY_KVARH_Q4 bigint, 
BLOCK_ENERGY_KVAH_IMP bigint, 
BLOCK_ENERGY_KVAH_EXP bigint, 
CUM_ENERGY_KWH_IMP bigint, 
CUM_ENERGY_KWH_EXP bigint, 
CUM_ENERGY_KVAH_IMP bigint, 
CUM_ENERGY_KVAH_EXP bigint, 
REACTIVE_ENG_HIGH bigint, 
REACTIVE_ENG_LOW bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint, 
RECORD_VEE_STATUS string, 
CUM_POWER_OFF_DURATION_MINS bigint, 
NUM_OF_POWER_FAILURES bigint, 
THRESHOLD_LIMIT_OF_VOLTAGE_SAG bigint, 
TOT_HARMONIC_ACT_POWER_RPH bigint, 
TOT_HARMONIC_ACT_POWER_YPH bigint, 
TOT_HARMONIC_ACT_POWER_BPH bigint, 
TOT_HARMONIC_REACT_POWER_RPH bigint, 
TOT_HARMONIC_REACT_POWER_YPH bigint, 
TOT_HARMONIC_REACT_POWER_BPH bigint, 
TERMINAL_COVER_REMOVE_CNT bigint, 
MTR_INT_OPERATING_STATUS string, 
THRESHOLD_LIMIT_OF_CUR_PEAK bigint, 
THRESHOLD_LIMIT_OF_VOL_PEAK bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




CREATE EXTERNAL TABLE IF NOT EXISTS MPM_EVENT_PARAMETERS(
EVENT_PARA_ID bigint, 
MTR_NO string, 
CLOCK TIMESTAMP, 
EVENT_CODE bigint, 
CUM_TAMPER_COUNT bigint, 
R_PH_CURRENT bigint, 
Y_PH_CURRENT bigint, 
B_PH_CURRENT bigint, 
R_PH_VOLTAGE bigint, 
Y_PH_VOLTAGE bigint, 
B_PH_VOLTAGE bigint, 
R_PH_POWER_FACTOR bigint, 
Y_PH_POWER_FCTOR bigint, 
B_PH_POWER_FACTOR bigint, 
SINGLE_PH_OR_TOT_PF bigint, 
CUM_ENERGY_KWH_IMP bigint, 
CUM_ENERGY_KWH_EXP bigint, 
SINGLE_PH_OR_TOT_CUR bigint, 
SINGLE_PH_OR_TOT_VOL bigint, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE, 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




CREATE EXTERNAL TABLE IF NOT EXISTS MPM_EVENT_PARAMETERS_DUMMY
(
MTR_NO string, 
CLOCK TIMESTAMP, 
EVENT_CODE bigint, 
CUM_TAMPER_COUNT bigint, 
R_PH_CURRENT bigint, 
Y_PH_CURRENT bigint, 
B_PH_CURRENT bigint, 
R_PH_VOLTAGE bigint, 
Y_PH_VOLTAGE bigint, 
B_PH_VOLTAGE bigint, 
R_PH_POWER_FACTOR bigint, 
Y_PH_POWER_FCTOR bigint, 
B_PH_POWER_FACTOR bigint, 
SINGLE_PH_OR_TOT_PF bigint, 
CUM_ENERGY_KWH_IMP bigint, 
CUM_ENERGY_KWH_EXP bigint, 
SINGLE_PH_OR_TOT_CUR bigint, 
SINGLE_PH_OR_TOT_VOL bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



CREATE EXTERNAL TABLE IF NOT EXISTS MPM_INSTANT_PARAMETERS(
INSTA_PARA_ID bigint, 
MTR_NO bigint, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
NUM_PWR_FAILURE bigint, 
CUM_PWR_OFF_DUR bigint, 
CUM_TAMPER_COUNT bigint, 
CUM_BILLING_COUNT bigint, 
CUM_PROGRAM_COUNT bigint, 
BILLING_DATE TIMESTAMP, 
CURRENT_IR bigint, 
CURRENT_IY bigint, 
CURRENT_IB bigint, 
VOLTAGE_VRN bigint, 
VOLTAGE_VYN bigint, 
VOLTAGE_VBN bigint, 
SIGNED_PWR_FACT_R_PH bigint, 
SIGNED_PWR_FACT_Y_PH bigint, 
SIGNED_PWR_FACT_B_PH bigint, 
SIGNED_PWR_FACT_PF bigint, 
FREQUENCY bigint, 
APPARENT_PWR_KVA bigint, 
SIGNED_ACTIVE_PWR_KW bigint, 
SIGNED_RECTIVE_PWR_KVAR bigint, 
CUM_ENG_KWH_IMP bigint, 
CUM_ENG_KWH_EXP bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint, 
CUM_ENG_KVAH_IMP bigint, 
CUM_ENG_KVAH_EXP bigint, 
MAX_DEMAND_KW_IMP bigint, 
MAX_DEMAND_KVA_IMP bigint, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE, 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string, 
RECORD_VEE_STATUS string, 
EDITED_BY string, 
EDITED_DATE TIMESTAMP, 
EDITED_REASON string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




CREATE EXTERNAL TABLE IF NOT EXISTS MPM_INSTANT_PARAMETERS_XML(
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
CURRENT_IR bigint, 
CURRENT_IY bigint, 
CURRENT_IB bigint, 
VOLTAGE_VRN bigint, 
VOLTAGE_VYN bigint, 
VOLTAGE_VBN bigint, 
SIGNED_PWR_FACT_R_PH bigint, 
SIGNED_PWR_FACT_Y_PH bigint, 
SIGNED_PWR_FACT_B_PH bigint, 
FREQUENCY bigint, 
APPARENT_PWR_KVA bigint, 
SIGNED_ACTIVE_PWR_KW bigint, 
SIGNED_RECTIVE_PWR_KVAR bigint, 
CUM_ENG_KWH_IMP bigint, 
CUM_ENG_KWH_EXP bigint, 
CUM_ENG_KVAH_IMP bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




CREATE EXTERNAL TABLE IF NOT EXISTS MPM_INSTA_PARA(
INSTA_PARA_ID bigint, 
MTR_NO bigint, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
NUM_PWR_FAILURE bigint, 
CUM_PWR_OFF_DUR bigint, 
CUM_TAMPER_COUNT bigint, 
CUM_BILLING_COUNT bigint, 
CUM_PROGRAM_COUNT bigint, 
BILLING_DATE TIMESTAMP, 
CURRENT_IR bigint, 
CURRENT_IY bigint, 
CURRENT_IB bigint, 
VOLTAGE_VRN bigint, 
VOLTAGE_VYN bigint, 
VOLTAGE_VBN bigint, 
SIGNED_PWR_FACT_R_PH bigint, 
SIGNED_PWR_FACT_Y_PH bigint, 
SIGNED_PWR_FACT_B_PH bigint, 
SIGNED_PWR_FACT_PF bigint, 
FREQUENCY bigint, 
APPARENT_PWR_KVA bigint, 
SIGNED_ACTIVE_PWR_KW bigint, 
SIGNED_RECTIVE_PWR_KVAR bigint, 
CUM_ENG_KWH_IMP bigint, 
CUM_ENG_KWH_EXP bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint, 
CUM_ENG_KVAH_IMP bigint, 
CUM_ENG_KVAH_EXP bigint, 
MAX_DEMAND_KW_IMP bigint, 
MAX_DEMAND_KVA_IMP bigint, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE, 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string, 
RECORD_VEE_STATUS string, 
EDITED_BY string, 
EDITED_DATE TIMESTAMP, 
EDITED_REASON string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




CREATE EXTERNAL TABLE IF NOT EXISTS MPM_JOB_REQUESTS(
REQUEST_ID bigint, 
REQUEST_PARAMETER string, 
REQUEST_NAME string, 
REQUEST_STATUS string, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string, 
MTR_NO bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");



CREATE EXTERNAL TABLE IF NOT EXISTS MPM_LOAD_PROFILE_PARA(
DAILY_LOAD_PARA_ID bigint, 
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
BATTERY_VOLTAGE bigint, 
GSM_FIELD_STRENGTH bigint, 
TELEPHONE_NO bigint, 
CURRENT_IR bigint, 
CURRENT_IY bigint, 
CURRENT_IB bigint, 
VOLTAGE_VRN bigint, 
VOLTAGE_VYN bigint, 
VOLTAGE_VBN bigint, 
BLOCK_ENERGY_KWH_IMP bigint, 
BLOCK_ENERGY_KWH_EXP bigint, 
BLOCK_ENERGY_KVARH_Q1 bigint, 
BLOCK_ENERGY_KVARH_Q2 bigint, 
BLOCK_ENERGY_KVARH_Q3 bigint, 
BLOCK_ENERGY_KVARH_Q4 bigint, 
BLOCK_ENERGY_KVAH_IMP bigint, 
BLOCK_ENERGY_KVAH_EXP bigint, 
REAL_TIME_CLOCK_DATE_TI TIMESTAMP, 
CUM_ENERGY_KWH_IMP bigint, 
CUM_ENERGY_KWH_EXP bigint, 
CUM_ENERGY_KVAH_IMP bigint, 
CUM_ENERGY_KVAH_EXP bigint, 
REACTIVE_ENG_HIGH bigint, 
REACTIVE_ENG_LOW bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint, 
RECORD_VEE_STATUS string, 
EDITED_BY string, 
EDITED_DATE TIMESTAMP, 
EDITED_REASON string, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE, 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




CREATE EXTERNAL TABLE IF NOT EXISTS MPM_MONTHLY_CONSUMPTION(
MONTHLY_CON_ID bigint, 
MTR_NO string, 
CONSUMPTION_DATE TIMESTAMP, 
CONSUMPTION bigint, 
AVG_CONSUMPTION bigint, 
VARIANCE bigint, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE, 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");





CREATE EXTERNAL TABLE IF NOT EXISTS MPM_MON_CON_DUMMY(
MTR_NO string, 
CONSUMPTION_DATE TIMESTAMP, 
CONSUMPTION bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");






CREATE EXTERNAL TABLE IF NOT EXISTS MPM_NAMEPLATE_XML(
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
COSEM_LOGIC_DEV_NAME string, 
METER_SERIAL_NUM string, 
MANUFACTURE_NAME string, 
DEVICE_ID string, 
METER_TYPE string, 
CATEGORY string, 
CURRENT_RATING bigint, 
METER_YEAR_MANUFACTURE bigint

)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");






CREATE EXTERNAL TABLE IF NOT EXISTS MPM_NAME_PLATE_PARA(
NAME_PLATE_PARA_ID bigint, 
MTR_NO bigint, 
METER_SERIAL_NUM string, 
MANUFACTURE_NAME string, 
DEVICE_ID string, 
METER_TYPE bigint, 
CATEGORY string, 
CURRENT_RATING string, 
METER_YEAR_MANUFACTURE bigint, 
FIRMWARE_VERSION_METER string, 
INTERNAL_CT_RATIO bigint, 
INTERNAL_VT_RATIO bigint, 
ACT_ENG_OUTPUT_PULSE bigint, 
RECT_ENG_OUTPUT_PULSE bigint, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE, 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string, 
COSEM_LOGIC_DEV_NAME string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");





CREATE EXTERNAL TABLE IF NOT EXISTS MPM_PROGRAM_ENTRY_OBJ(
PROGRAM_OBJ_ID bigint, 
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME bigint, 
SINGLE_ACT_SCH_BILLING_DT string, 
ACTIVITY_CALE_TIMEZONE string, 
RS485_DEVICE_ADDRESS string, 
IMAGE_TRANSFER string, 
LLS_SECRET string, 
HLS_KEY string, 
GLOBAL_KEY_CHANGE string, 
IMAGE_ACT_SINGLE_ACT_SCH string, 
ESWF string, 
METERING_MODE string, 
MD_RESET string, 
DEMAND_INTEGRATION_PERIOD bigint, 
PROFILE_CAPTURE_PERIOD string, 
MEAS_ALG_ACT_PWR bigint, 
MEAS_ALG_ACT_ENG bigint, 
MEAS_ALG_REACT_PWR bigint, 
MEAS_ALG_REACT_ENG bigint, 
MEAS_ALG_APP_PWR bigint, 
MEAS_ALG_APP_ENG bigint, 
MEAS_ALG_PWR_FACT bigint, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE, 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");







CREATE EXTERNAL TABLE IF NOT EXISTS MPM_PROGRAM_ENTRY_OBJ_DUMMY(
PROGRAM_OBJ_ID bigint, 
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME bigint, 
SINGLE_ACT_SCH_BILLING_DT string, 
ACTIVITY_CALE_TIMEZONE string, 
RS485_DEVICE_ADDRESS string, 
IMAGE_TRANSFER string, 
LLS_SECRET string, 
HLS_KEY string, 
GLOBAL_KEY_CHANGE string, 
IMAGE_ACT_SINGLE_ACT_SCH string, 
ESWF string, 
METERING_MODE string, 
MD_RESET string, 
DEMAND_INTEGRATION_PERIOD bigint, 
PROFILE_CAPTURE_PERIOD string, 
MEAS_ALG_ACT_PWR bigint, 
MEAS_ALG_ACT_ENG bigint, 
MEAS_ALG_REACT_PWR bigint, 
MEAS_ALG_REACT_ENG bigint, 
MEAS_ALG_APP_PWR bigint, 
MEAS_ALG_APP_ENG bigint, 
MEAS_ALG_PWR_FACT bigint, 
RECORD_STATUS string, 
CREATION_DATE DATE, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");






CREATE EXTERNAL TABLE IF NOT EXISTS RAW_BILLING(
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
BILLING_DATE TIMESTAMP, 
SYS_PWR_FACT_BILLING_PERIOD bigint, 
CUM_ENG_KWH bigint, 
CUM_ENG_KWH_TZ_1 bigint, 
CUM_ENG_KWH_TZ_2 bigint, 
CUM_ENG_KWH_TZ_3 bigint, 
CUM_ENG_KWH_TZ_4 bigint, 
CUM_ENG_KWH_TZ_5 bigint, 
CUM_ENG_KWH_TZ_6 bigint, 
CUM_ENG_KWH_TZ_7 bigint, 
CUM_ENG_KWH_TZ_8 bigint, 
CUM_ENG_KVARH_LAG bigint, 
CUM_ENG_KVARH_LEAD bigint, 
CUM_ENG_KVAH bigint, 
CUM_ENG_KVAH_TZ_1 bigint, 
CUM_ENG_KVAH_TZ_2 bigint, 
CUM_ENG_KVAH_TZ_3 bigint, 
CUM_ENG_KVAH_TZ_4 bigint, 
CUM_ENG_KVAH_TZ_5 bigint, 
CUM_ENG_KVAH_TZ_6 bigint, 
CUM_ENG_KVAH_TZ_7 bigint, 
CUM_ENG_KVAH_TZ_8 bigint, 
MD_KW bigint, 
MD_KW_TZ_1 bigint, 
MD_KW_TZ_2 bigint, 
MD_KW_TZ_3 bigint, 
MD_KW_TZ_4 bigint, 
MD_KW_TZ_5 bigint, 
MD_KW_TZ_6 bigint, 
MD_KW_TZ_7 bigint, 
MD_KW_TZ_8 bigint, 
MD_KVA bigint, 
MD_KVA_TZ_1 bigint, 
MD_KVA_TZ_2 bigint, 
MD_KVA_TZ_3 bigint, 
MD_KVA_TZ_4 bigint, 
MD_KVA_TZ_5 bigint, 
MD_KVA_TZ_6 bigint, 
MD_KVA_TZ_7 bigint, 
MD_KVA_TZ_8 bigint, 
CUM_ENG_KWH_EXP bigint, 
CUM_ENG_KVAH_EXP bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");






CREATE EXTERNAL TABLE IF NOT EXISTS RAW_EVENTSLOG(
MTR_NO string, MTR_NO string, 
CLOCK TIMESTAMP, 
EVENT_CODE string, 
CUM_TAMPER_COUNT bigint, 
R_PH_CURRENT bigint, 
Y_PH_CURRENT bigint, 
B_PH_CURRENT bigint, 
R_PH_VOLTAGE bigint, 
Y_PH_VOLTAGE bigint, 
B_PH_VOLTAGE bigint, 
R_PH_POWER_FACTOR bigint, 
Y_PH_POWER_FCTOR bigint, 
B_PH_POWER_FACTOR bigint, 
SINGLE_PH_OR_TOT_PF bigint, 
CUM_ENERGY_KWH_IMP bigint, 
CUM_ENERGY_KWH_EXP bigint, 
SINGLE_PH_OR_TOT_CUR bigint, 
SINGLE_PH_OR_TOT_VOL bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");






CREATE EXTERNAL TABLE IF NOT EXISTS RAW_INSTANTANEOUS(
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
NUM_PWR_FAILURE bigint, 
CUM_PWR_OFF_DUR bigint, 
CUM_TAMPER_COUNT bigint, 
CUM_BILLING_COUNT bigint, 
CUM_PROGRAM_COUNT bigint, 
BILLING_DATE TIMESTAMP, 
CURRENT_IR bigint, 
CURRENT_IY bigint, 
CURRENT_IB bigint, 
VOLTAGE_VRN bigint, 
VOLTAGE_VYN bigint, 
VOLTAGE_VBN bigint, 
SIGNED_PWR_FACT_R_PH bigint, 
SIGNED_PWR_FACT_Y_PH bigint, 
SIGNED_PWR_FACT_B_PH bigint, 
SIGNED_PWR_FACT_PF bigint, 
FREQUENCY bigint, 
APPARENT_PWR_KVA bigint, 
SIGNED_ACTIVE_PWR_KW bigint, 
SIGNED_RECTIVE_PWR_KVAR bigint, 
CUM_ENG_KWH_IMP bigint, 
CUM_ENG_KWH_EXP bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint, 
CUM_ENG_KVAH_IMP bigint, 
CUM_ENG_KVAH_EXP bigint, 
MAX_DEMAND_KW_IMP bigint, 
MAX_DEMAND_KVA_IMP bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




CREATE EXTERNAL TABLE IF NOT EXISTS RAW_NAMEPLATE(
MTR_NO string, 
METER_SERIAL_NUM string, 
MANUFACTURE_NAME string, 
DEVICE_ID string, 
METER_TYPE bigint, 
CATEGORY string, 
CURRENT_RATING string, 
METER_YEAR_MANUFACTURE bigint, 
FIRMWARE_VERSION_METER string, 
INTERNAL_CT_RATIO bigint, 
INTERNAL_VT_RATIO bigint, 
ACT_ENG_OUTPUT_PULSE bigint, 
RECT_ENG_OUTPUT_PULSE bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");





CREATE EXTERNAL TABLE IF NOT EXISTS RAW_PROGRAM_OBJECTS(
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME bigint, 
SINGLE_ACT_SCH_BILLING_DT string, 
ACTIVITY_CALE_TIMEZONE string, 
RS485_DEVICE_ADDRESS string, 
IMAGE_TRANSFER string, 
LLS_SECRET string, 
HLS_KEY string, 
GLOBAL_KEY_CHANGE string, 
IMAGE_ACT_SINGLE_ACT_SCH string, 
ESWF string, 
METERING_MODE string, 
MD_RESET string, 
DEMAND_INTEGRATION_PERIOD bigint, 
PROFILE_CAPTURE_PERIOD string, 
MEAS_ALG_ACT_PWR bigint, 
MEAS_ALG_ACT_ENG bigint, 
MEAS_ALG_REACT_PWR bigint, 
MEAS_ALG_REACT_ENG bigint, 
MEAS_ALG_APP_PWR bigint, 
MEAS_ALG_APP_ENG bigint, 
MEAS_ALG_PWR_FACT bigint
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




CREATE EXTERNAL TABLE IF NOT EXISTS VEE_ME_BILLING_PARAMETERS
(
MTR_NO string, 
REAL_TIME_CLOCK_DATE_TIME TIMESTAMP, 
BILLING_DATE TIMESTAMP, 
SYS_PWR_FACT_BILLING_PERIOD bigint, 
CUM_ENG_KWH bigint, 
CUM_ENG_KWH_TZ_1 bigint, 
CUM_ENG_KWH_TZ_2 bigint, 
CUM_ENG_KWH_TZ_3 bigint, 
CUM_ENG_KWH_TZ_4 bigint, 
CUM_ENG_KWH_TZ_5 bigint, 
CUM_ENG_KWH_TZ_6 bigint, 
CUM_ENG_KWH_TZ_7 bigint, 
CUM_ENG_KWH_TZ_8 bigint, 
CUM_ENG_KVARH_LAG bigint, 
CUM_ENG_KVARH_LEAD bigint, 
CUM_ENG_KVAH bigint, 
CUM_ENG_KVAH_TZ_1 bigint, 
CUM_ENG_KVAH_TZ_2 bigint, 
CUM_ENG_KVAH_TZ_3 bigint, 
CUM_ENG_KVAH_TZ_4 bigint, 
CUM_ENG_KVAH_TZ_5 bigint, 
CUM_ENG_KVAH_TZ_6 bigint, 
CUM_ENG_KVAH_TZ_7 bigint, 
CUM_ENG_KVAH_TZ_8 bigint, 
MD_KW bigint, 
MD_KW_TZ_1 bigint, 
MD_KW_TZ_2 bigint, 
MD_KW_TZ_3 bigint, 
MD_KW_TZ_4 bigint, 
MD_KW_TZ_5 bigint, 
MD_KW_TZ_6 bigint, 
MD_KW_TZ_7 bigint, 
MD_KW_TZ_8 bigint, 
MD_KVA bigint, 
MD_KVA_TZ_1 bigint, 
MD_KVA_TZ_2 bigint, 
MD_KVA_TZ_3 bigint, 
MD_KVA_TZ_4 bigint, 
MD_KVA_TZ_5 bigint, 
MD_KVA_TZ_6 bigint, 
MD_KVA_TZ_7 bigint, 
MD_KVA_TZ_8 bigint, 
CUM_ENG_KWH_EXP bigint, 
CUM_ENG_KVAH_EXP bigint, 
CUM_ENG_KVARH_Q1 bigint, 
CUM_ENG_KVARH_Q2 bigint, 
CUM_ENG_KVARH_Q3 bigint, 
CUM_ENG_KVARH_Q4 bigint, 
PF bigint, 
BLCK_ENG_KWH bigint, 
BLCK_ENG_KVAH bigint, 
RECORD_VEE_STATUS string, 
EDITED_BY string, 
EDITED_DATE TIMESTAMP, 
EDITED_REASON string, 
RECORD_STATUS string, 
CREATED_BY bigint, 
CREATION_DATE DATE, 
LAST_UPDATED_BY bigint, 
LAST_UPDATE_DATE DATE, 
LAST_UPDATE_LOGIN bigint, 
SERVER_IP string, 
ATTRIBUTE1 string, 
ATTRIBUTE2 string, 
ATTRIBUTE3 string, 
ATTRIBUTE4 string, 
ATTRIBUTE5 string, 
ATTRIBUTE6 string, 
ATTRIBUTE7 string, 
ATTRIBUTE8 string, 
ATTRIBUTE9 string, 
ATTRIBUTE10 string
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");




CREATE EXTERNAL TABLE IF NOT EXISTS MPM.MPM_DAILY_CONSUMPTION(
DAILY_CON_ID bigint,
MTR_NO string,
CONSUMPTION_DATE TIMESTAMP,
CONSUMPTION bigint,
AVG_CONSUMPTION bigint,
VARIANCE bigint,
RECORD_STATUS string,
CREATED_BY bigint,
CREATION_DATE DATE,
LAST_UPDATED_BY bigint,
LAST_UPDATE_DATE DATE,
LAST_UPDATE_LOGIN bigint,
SERVER_IP string,
ATTRIBUTE1 string
ATTRIBUTE2 string
ATTRIBUTE3 string
ATTRIBUTE4 string
ATTRIBUTE5 string
ATTRIBUTE6 string
ATTRIBUTE7 string
ATTRIBUTE8 string
ATTRIBUTE9 string
ATTRIBUTE10 string  
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");


